[antlir2] fail fast and obviously when trying receive sendstreams in OD
Summary:
Now that we can actually build a lot of images in OD, this is just going to get
more confusing until it actually works

Test Plan:
```name="Fails in OD",counterexample
[vmagro@71399.od /data/sandcastle/boxes/fbsource (951229e3d|remote/fbcode/warm_fbcode_od_stable...)]$ buck build fbcode//tupperware/image/base:base.c9
File changed: fbcode//tupperware/image/base/TARGETS
Buck UI: https://www.internalfb.com/buck2/43ff47a0-ccb3-435b-ac16-2414f6bf272e
Jobs completed: 86914. Time elapsed: 10.3s.
BUILD FAILED
Error running analysis for `fbcode//tupperware/image/base:base.c9 (cfg:linux-x86_64-fbcode-platform010-asan-ubsan-dev#b007eb344207ad7d)`

Caused by:
    0: Error running analysis for `fbcode//tupperware/image/base:base (cfg:linux-x86_64-fbcode-platform010-asan-ubsan-dev#a56618698188fcd3)`
    1: Error running analysis for `fbcode//tupperware/image/base:base--prebuilt (cfg:linux-x86_64-fbcode-platform010-asan-ubsan-dev#a56618698188fcd3)`
    2: Traceback (most recent call last):
         File <builtin>, in <module>
         * fbcode/antlir/antlir2/bzl/image/prebuilt.bzl:45, in _impl
             fail("sendstream images cannot yet be received in OnDemand")
       error: fail: sendstream images cannot yet be received in OnDemand
         --> fbcode/antlir/antlir2/bzl/image/prebuilt.bzl:45:9
          |
       45 |         fail("sendstream images cannot yet be received in OnDemand")
          |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

```name="Still works in devvm"
❯ buck2 build --show-full-output fbcode//tupperware/image/base:base.c9
Buck UI: https://www.internalfb.com/buck2/3dcc0244-faaa-457c-b3fb-806bbf44c2b7
Note:    Using experimental modern dice
Network: Up: 36KiB  Down: 153MiB  (reSessionID-9902ba81-0a97-4a62-9235-0de27a2462cf)
Jobs completed: 155469. Time elapsed: 20.3s.
Cache hits: 99%. Commands: 349 (cached: 348, remote: 0, local: 1)
BUILD SUCCEEDED
fbcode//tupperware/image/base:base.c9 /data/users/vmagro/fbsource/buck-out/v2/gen/fbcode/71ebdec9ac36a01d/tupperware/image/base/__base--prebuilt__/subvol_symlink
```

Reviewed By: sergeyfd

Differential Revision: D53436268

fbshipit-source-id: cdfe8c28ab89c0740fbd684e3137f6634532dce2