[antlir][oss] disable experimental zstd feature
Summary:
This is why we're getting errors like
```
❯ buck build antlir//antlir/antlir2/features/tarball/tests:tarball
Action failed: antlir//antlir/antlir2/features/tarball/tests:tarball (antlir2_feature_analyze compile/tarball[0])
Local command returned non-zero exit code 1
Reproduce locally: `env -- 'BUCK_SCRATCH_PATH=buck-out/v2/tmp/antlir/4d2ef6eeff94964d/antlir2_feature_analyze/compile/ta ...<omitted>... antlir/antlir2/features/tarball/tests/__tarball__/compile/features/compile/tarball[0].analyzed.json' (run `buck2 log what-failed` to get the full command)`
stdout:
stderr:
Error: while determining feature requires

Caused by:
    could not load plugin: buck-out/v2/gen/antlir/1cd7095141bd4987/antlir/antlir2/features/tarball/__tarball__/tarball.so: undefined symbol: ZSTD_createThreadPool
```

Test Plan: GitHub Actions

Differential Revision: D59683732