Make sure /run/fs/control/run/state/metalos is on the root disk image
Summary:
While testing my native service (built by using the native_service buck function) I found out that the directory is missing in the root disk GPT image:

```
[root@rsw1dq ~]# metalctl-dev service start metalos.netos.wedge400c_platform_layer:524ff6641bc534956fe6fcc4cc79baa0
V0401 07:42:58.973017  1744 [main] metalos/metalctl/dev/src/service.rs:71] opening sendstream https connection, dest: "/run/fs/control/image/service/metalos.netos.wedge400c_platform_layer:524ff6641bc534956fe6fcc4cc79baa0", package: Image(AnyImage { name: ImageName("metalos.netos.wedge400c_platform_layer"), id: ImageID("524ff6641bc534956fe6fcc4cc79baa0"), kind: Service, override_uri: None }, PhantomData)
V0401 07:43:22.196487  1744 [main] metalos/metalctl/dev/src/service.rs:76] receiving sendstream, dest: "/run/fs/control/image/service/metalos.netos.wedge400c_platform_layer:524ff6641bc534956fe6fcc4cc79baa0", package: Image(AnyImage { name: ImageName("metalos.netos.wedge400c_platform_layer"), id: ImageID("524ff6641bc534956fe6fcc4cc79baa0"), kind: Service, override_uri: None }, PhantomData)
V0401 07:43:33.534979  1744 [main] metalos/lib/service/src/service.rs:288] preparing to start metalos.netos.wedge400c_platform_layer:524ff6641bc534956fe6fcc4cc79baa0, current: ServiceSet({}), next: ServiceSet({"metalos.netos.wedge400c_platform_layer": 524ff664-1bc5-3495-6fe6-fcc4cc79baa0})
Error: while preparing to start metalos.netos.wedge400c_platform_layer:524ff6641bc534956fe6fcc4cc79baa0

Caused by:
    0: while building dropin for metalos.netos.wedge400c_platform_layer.service
    1: while saving ServiceInstance to the state store
    2: while creating /run/fs/control/run/state/metalos/service::ServiceInstance-aa5f4816-8cc4-4b47-baad-d7adaefa77e2.json
    3: No such file or directory (os error 2)
```

Reviewed By: vmagro

Differential Revision: D35315655

fbshipit-source-id: 8ab637230b0d2de454a0e73cb7ec7658b4cef6c3