[antlir] Fix broken Pyre config
Summary:
Our Antlir Pyre config has been broken for a while due to a bug in buck2 uquery (which Pyre uses by default) when using rdeps: T139638000

To fix this, I've opted to instead stamp the remaining places in our macro layers where we weren't setting `no_pyre` even though we were taking a layer dep, then simplified our Pyre config to just cover all of Antlir. This may overmatch on some of our Python unit test targets, but typing tends to not really be useful in unittests anyways due to mocking and such so I'm not overly worried.

Test Plan:
I opted to add a dumb unit test that queries our Antlir to hopefully catch this error on-diff if it crops up again (Pyre doesn't seem to omit a red signal on the diff if the query becomes borked in past experience). Tested it by removing one of the fixes present in this diff:

```
$ buck2 test //antlir/facebook:test-pyre-config
2023-01-19T19:22:43.399746Z  WARN buck2_core::error: Important warning at buck2/app/buck2_server_ctx/src/concurrency.rs:359:17 Recursive invocation of Buck, which is discouraged, but will probably work (using the same state). Trace Ids: dabdf0d0-6071-4d37-bb1b-5b7dcd744754, 916a6461-8f3e-49a7-a66b-03dac5768826. Recur
sive invocation CLI args: [/data/users/jtru/fbsource/.buck2, cquery, --reuse-current-config, kind("python_binary|python_library|python_test", %s) - attrfilter(labels, generated, %s) + attrfilter(labels, unittest-library, %s) - attrfilter(labels, no_pyre, %s), attrfilter(labels, 'image_layer', 'fbcode//antlir/...') +
rdeps('//antlir/...', attrfilter(labels, 'image_layer', 'fbcode//antlir/...'))]
✗ Fail: antlir/facebook:test-pyre-config - test_no_layers_in_antlir_deps (antlir.facebook.tests.test_pyre_config.PyreConfigTestCase) (7.4s)

test_no_layers_in_antlir_deps (antlir.facebook.tests.test_pyre_config.PyreConfigTestCase) ... [2023-01-19T11:22:43.410-08:00] RE Session: reSessionID-5c4f7b0a-0366-43ad-a08d-0c68d47c200d
[2023-01-19T11:22:43.410-08:00] Build ID: 916a6461-8f3e-49a7-a66b-03dac5768826
[2023-01-19T11:22:43.582-08:00] 2023-01-19T19:22:43.399746Z  WARN buck2_core::error: Important warning at buck2/app/buck2_server_ctx/src/concurrency.rs:359:17 Recursive invocation of Buck, which is discouraged, but will probably work (using the same state). Trace Ids: dabdf0d0-6071-4d37-bb1b-5b7dcd744754, 916a6461-8f
3e-49a7-a66b-03dac5768826. Recursive invocation CLI args: [/data/users/jtru/fbsource/.buck2, cquery, --reuse-current-config, kind("python_binary|python_library|python_test", %s) - attrfilter(labels, generated, %s) + attrfilter(labels, unittest-library, %s) - attrfilter(labels, no_pyre, %s), attrfilter(labels, 'image_
layer', 'fbcode//antlir/...') + rdeps('//antlir/...', attrfilter(labels, 'image_layer', 'fbcode//antlir/...'))]
[2023-01-19T11:22:50.518-08:00] RE: reSessionID-5c4f7b0a-0366-43ad-a08d-0c68d47c200d  Up: 124 B  Down: 0 B
FAIL

======================================================================
FAIL: test_no_layers_in_antlir_deps (antlir.facebook.tests.test_pyre_config.PyreConfigTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/jtru/fbsource/buck-out/v2/gen/fbcode/544943cfd42425fb/antlir/facebook/__test-pyre-config__/test-pyre-config#link-tree/antlir/facebook/tests/test_pyre_config.py", line 27, in test_no_layers_in_antlir_deps
    self.assertFalse(
AssertionError: 'fbcode//antlir/rpm/replay/tests:test-extract-nested-features (ovr_config//platform/linux:x86_64-fbcode-platform010-clang-544943cfd42425fb)' is not false : Expected no targets to depend on layers that do not have no_pyre label. If you are adding a new macro that generates Python targets, be sure to la
bel it with `no_pyre` if it will depend on image layers. Got the following targets:
fbcode//antlir/rpm/replay/tests:test-extract-nested-features (ovr_config//platform/linux:x86_64-fbcode-platform010-clang-544943cfd42425fb)

----------------------------------------------------------------------
Ran 1 test in 7.417s

FAILED (failures=1)
```

Reviewed By: epilatow

Differential Revision: D42613535

fbshipit-source-id: 1821c4e7297eb67db836331d27cfd894839aeefb