tee: Preload jemalloc deps automatically for antlir distro PAR builds
Summary:
This is required, otherwise you run into the following:
```
$ buck run fbcode//mode/opt fbcode//tee/snp/image/examples/sidecar:cvm_sidecar_image[container]
File changed: fbcode_macros//build_defs/lib/python_common.bzl
File changed: fbcode//tee/orchestrator/server/BUCK
File changed: fbcode//tee/snp/image/examples/sidecar/BUCK
1 additional file change events
File changed: fbcode_macros//build_defs/lib/python_common.bzl
Buck UI: https://www.internalfb.com/buck2/d9ca0084-941d-47ee-8a6c-59e3ec22950e
Network: Up: 69MiB  Down: 661MiB  (reSessionID-9258d293-83f7-4c1a-9c99-19c5aa09c637)
Loading targets.   Remaining      0/39306                                    899747 targets declared
Analyzing targets. Remaining      0/130602                                   685047 actions, 721068 artifacts declared
Executing actions. Remaining      0/140279                                   9.8s exec time total
Command: run.      Finished 8 local
Time elapsed: 25.4s
BUILD SUCCEEDED - starting your binary

bash-5.1# /usr/local/bin/orchestrator --help
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/bin/orchestrator/__main__.py", line 986, in <module>
  File "/usr/local/bin/orchestrator/__main__.py", line 983, in __invoke_main
  File "/usr/local/bin/orchestrator/__main__.py", line 607, in main
  File "__par__/meta_only/bootstrap.py", line 98, in run_as_main
  File "__par__/bootstrap.py", line 74, in run_as_main
  File "/usr/lib64/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "tee/orchestrator/server/main.py", line 7, in <module>
  File "/usr/local/bin/orchestrator/__main__.py", line 923, in load_module
ImportError: /tmp/par_unpack.main.0.3aa8bdd80b7b429a9352d5833eae17dd/./libjemalloc.so.2: cannot allocate memory in static TLS block
```
Do this by default for antlir distro deps in the macro layer so not every rule needs to specify this preload dep if it wants to run in TEE.

Test Plan:
Build orchestrator, it runs (but still fails on a missing symbol):
```
$ buck run fbcode//mode/opt fbcode//tee/snp/image/examples/sidecar:cvm_sidecar_image[container]
File changed: fbcode//tee/orchestrator/server/BUCK
File changed: fbcode_macros//build_defs/lib/python_common.bzl
File changed: fbcode//tee/snp/image/examples/sidecar/BUCK
1 additional file change events
Buck UI: https://www.internalfb.com/buck2/d8695a9f-0ad2-4f19-967a-08e78da78e85
Network: Up: 324B  Down: 661MiB  (reSessionID-1aa99e95-0a5b-4a7c-b813-0150cdfd38a4)
Loading targets.   Remaining      0/39306                                    1 dirs read, 899747 targets declared
Analyzing targets. Remaining      0/130602                                   687125 actions, 723279 artifacts declared
Executing actions. Remaining      0/140280                                   9.7s exec time total
Command: run.      Finished 6 local, 2 cache (25% hit)                       0.6s exec time cached (5%)
Time elapsed: 24.8s
BUILD SUCCEEDED - starting your binary
bash-5.1# /usr/local/bin/orchestrator --help
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/bin/orchestrator/__main__.py", line 986, in <module>
  File "/usr/local/bin/orchestrator/__main__.py", line 983, in __invoke_main
  File "/usr/local/bin/orchestrator/__main__.py", line 607, in main
  File "__par__/meta_only/bootstrap.py", line 98, in run_as_main
  File "__par__/bootstrap.py", line 74, in run_as_main
  File "/usr/lib64/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "tee/orchestrator/server/main.py", line 7, in <module>
  File "/usr/local/bin/orchestrator/__main__.py", line 923, in load_module
ImportError: /tmp/par_unpack.main.0.023e9b706ae3e08228ab80267dd59951/./libomnibus.so: undefined symbol: MallocExtension_Internal_GetNumericProperty
```

Rollback Plan:

Reviewed By: zsol

Differential Revision: D77314648

fbshipit-source-id: 0d7d0833914490959474f61c681226cf25b0b6eb