[antlir2][testing] image rpm names test
Summary:
Antlir1 offers this but the macro is a little bit of a nightmare and does not
play nicely with antlir2.
Plus, we can do better with antlir2 anyway, and this test can eventually be
updated to just read from a manifest of installed rpms that can just be a
separate artifact on the LayerInfo provider

Test Plan:
```
❯ buck2 test fbcode//antlir/antlir2/testing/tests:test-foo-rpm-names
Buck UI: https://www.internalfb.com/buck2/3d80dc75-4a08-4681-be97-0e500a1db074
Test UI: https://www.internalfb.com/intern/testinfra/testrun/4503599795531778
RE: reSessionID-2f5d0a6c-4d1f-48a9-ba7f-e6d7dd5e65b9  Up: 62 B  Down: 0 B
Jobs completed: 228153. Time elapsed: 7.3s.
Tests finished: Pass 1. Fail 0. Fatal 0. Skip 0. 0 builds failed
```

Test the update flow
```
❯ hg diff
 diff --git a/fbcode/antlir/antlir2/testing/tests/foo-rpms.txt b/fbcode/antlir/antlir2/testing/tests/foo-rpms.txt
 --- a/fbcode/antlir/antlir2/testing/tests/foo-rpms.txt
+++ b/fbcode/antlir/antlir2/testing/tests/foo-rpms.txt
@@ -1,3 +1,2 @@
 foo                  0 bytes required by foobar
-foobar               0 bytes required by foobarbaz
 foobarbaz            0 bytes

vmagro@devbig928.frc1 in fbsource
❯ buck test fbcode//antlir/antlir2/testing/tests:test-foo-rpm-names
❯ buck2 test fbcode//antlir/antlir2/testing/tests:test-foo-rpm-names
✗ Fail: antlir/antlir2/testing/tests:test-foo-rpm-names - main (0.2s)
Test returned with non-zero exit code
stdout:
thread 'main' panicked at 'assertion failed: `(expected == installed)`: Installed rpms don't match. `buck run` this test with `-- --print` to generate a new source file'
  expected: `"{\"foo\", \"foobarbaz\"}"`
 installed: `"{\"foo\", \"foobar\", \"foobarbaz\"}"`

Differences (-expected|+installed):
 {
     "foo",
+    "foobar",
     "foobarbaz",
 }

', antlir/antlir2/testing/image_rpms_test/src/main.rs:126:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

stderr:
Buck UI: https://www.internalfb.com/buck2/4bf6d41c-630d-41a4-b3b3-b934eb91235b
Test UI: https://www.internalfb.com/intern/testinfra/testrun/7599824524634347
RE: reSessionID-14d84599-b1a7-4277-bb20-5fa79ab75d96  Up: 62 B  Down: 0 B
Jobs completed: 3. Time elapsed: 5.4s.
Tests finished: Pass 0. Fail 1. Fatal 0. Skip 0. 0 builds failed
1 TESTS FAILED
  ✗ antlir/antlir2/testing/tests:test-foo-rpm-names - main

❯ buck2 run fbcode//antlir/antlir2/testing/tests:test-foo-rpm-names -- -- --print
Buck UI: https://www.internalfb.com/buck2/68022727-d597-4294-9b1e-8c9ccae1a181
Jobs completed: 9. Time elapsed: 0.0s.
foo                  0 bytes required by foobar
foobar               0 bytes required by foobarbaz
foobarbaz            0 bytes
```

Reviewed By: epilatow

Differential Revision: D45456942

fbshipit-source-id: 035b39c9478407adef0df54299be6e8aa0471285