[antlir2][sendstream] incremental sendstream build support
Summary:
We may or may not be able to actually make use of these in prod, but figured
that it's a very small diff to support them, so I decided to do that

Test Plan:
```
❯ buck2 build --show-output fbcode//antlir/antlir2/test_images/package:incremental.sendstream.v2
BUILD SUCCEEDED
fbcode//antlir/antlir2/test_images/package:incremental.sendstream.v2 buck-out/v2/gen/fbcode/fdd3fedc5f835a2f/antlir/antlir2/test_images/package/__incremental.sendstream.v2__/image.sendstream.v2

❯ cat buck-out/v2/gen/fbcode/fdd3fedc5f835a2f/antlir/antlir2/test_images/package/__incremental.sendstream.v2__/image.sendstream.v2 | btrfs receive --dump
snapshot        ./volume                        uuid=554f7fa0-25be-8a4d-954b-cc5c8030610b transid=122419 parent_uuid=8e7cee6f-9b61-184d-9b19-3d328348605a parent_transid=122416
utimes          ./volume/                       atime=2023-10-06T12:22:48-0700 mtime=2023-10-06T12:22:57-0700 ctime=2023-10-06T12:22:57-0700
mkfile          ./volume/o258-122419-0
rename          ./volume/o258-122419-0          dest=./volume/bar
utimes          ./volume/                       atime=2023-10-06T12:22:48-0700 mtime=2023-10-06T12:22:57-0700 ctime=2023-10-06T12:22:57-0700
write           ./volume/bar                    offset=0 len=3
chown           ./volume/bar                    gid=0 uid=0
chmod           ./volume/bar                    mode=444
utimes          ./volume/bar                    atime=2023-10-06T12:22:57-0700 mtime=2023-10-06T12:22:57-0700 ctime=2023-10-06T12:22:57-0700
```

Prevent random disconnected subvols from being used:
```
❯ hg diff
 diff --git a/fbcode/antlir/antlir2/test_images/package/TARGETS b/fbcode/antlir/antlir2/test_images/package/TARGETS
 --- a/fbcode/antlir/antlir2/test_images/package/TARGETS
+++ b/fbcode/antlir/antlir2/test_images/package/TARGETS
@@ -153,6 +153,6 @@

 package.sendstream_v2(
     name = "incremental.sendstream.v2",
-    incremental_parent = ":incremental-parent",
+    incremental_parent = ":btrfs-test-1",
     layer = ":incremental-child",
 )

vmagro@devbig928.frc1 in fbsource
❯ buck build fbcode//antlir/antlir2/test_images/package:incremental.sendstream.v2
❯ buck2 build --show-output fbcode//antlir/antlir2/test_images/package:incremental.sendstream.v2
File changed: fbcode//antlir/antlir2/bzl/package/sendstream.bzl
Error running analysis for `fbcode//antlir/antlir2/test_images/package:incremental.sendstream.v2 (ovr_config//platform/linux:x86_64-fbcode-platform010-clang15#fdd3fedc5f835a2f)`

Caused by:
    Traceback (most recent call last):
      File <builtin>, in <module>
      * fbcode/antlir/antlir2/bzl/package/sendstream.bzl:45, in _impl
          fail("{} is not an ancestor of {}".format(
    error: fail: fbcode//antlir/antlir2/test_images/package:btrfs-test-1 is not an ancestor of fbcode//antlir/antlir2/test_images/package:incremental-child
      --> fbcode/antlir/antlir2/bzl/package/sendstream.bzl:45:13
       |
    45 |               fail("{} is not an ancestor of {}".format(
       |  _____________^
    46 | |                 incremental_parent.label.raw_target(),
    47 | |                 ctx.attrs.layer.label.raw_target(),
    48 | |             ))
       | |______________^
       |

Buck UI: https://www.internalfb.com/buck2/802c6e33-9bba-42b1-84e6-d64080df3ca3
Network: Up: 0B  Down: 0B
Jobs completed: 12. Time elapsed: 3.3s.
BUILD FAILED
```

Reviewed By: epilatow

Differential Revision: D50023999

fbshipit-source-id: 47fd203bee62b010e2abec5e49cf7dfdd42df5b9