[antlir2][chef_solo] ignore already-installed packages when looking at optional slowroll names
Summary:
`node.rpm_version` can return something if *another* package provides this
name. It does not mean that this `optional_package_name` is actually
installable.

This diff updates antlir2 to ignore already-installed packages so that it can't
be broken by this case (example: `systemd-timesyncd` is provided by
`systemd-udev` in centos10, so `systemd-timesyncd` cannot be installed
directly, but `fb_slowroll` assumes that it can)

Test Plan:
```name="With test but not code change",counterexample
❯ buck2 test fbcode//antlir/antlir2/features/facebook/chef_solo/tests:test-slowroll-optional-cannot-be-installed
[2024-07-16T21:50:26.460+00:00] INFO: ANTLIR2_CHEF_PLAN: beginning evaluation
[2024-07-16T21:50:26.460+00:00] WARN: ANTLIR2_CHEF_PLAN: fb_dnf_modularity[manage modularity] didn't exist
[2024-07-16T21:50:26.460+00:00] INFO: ANTLIR2_CHEF_PLAN: found 2 total package resources
[2024-07-16T21:50:26.475+00:00] INFO: ANTLIR2_CHEF_PLAN: processing antlir2_test_chef_solo_optional fb_slowroll [:manage]
[2024-07-16T21:50:26.475+00:00] INFO: ANTLIR2_CHEF_PLAN: looking at slowroll resource antlir2_test_chef_solo_optional
[2024-07-16T21:50:26.535+00:00] INFO: fb_slowroll[antlir2_test_chef_solo_optional] set to stable version because everything is stable
[2024-07-16T21:50:26.536+00:00] INFO: ANTLIR2_CHEF_PLAN:: checking fb_slowroll attributes for antlir2_test_chef_solo_optional
[2024-07-16T21:50:26.536+00:00] INFO: ANTLIR2_CHEF_PLAN:: pkginfo antlir2_test_chef_solo_optional exists
[2024-07-16T21:50:31.978+00:00] INFO: ANTLIR2_CHEF_PLAN:: using version 1 from antlir2-slowrolled for all packages in this slowroll: ["antlir2-slowrolled", "antlir2-slowrolled-optional-provided-by-other"]
[2024-07-16T21:50:32.076+00:00] INFO: ANTLIR2_CHEF_PLAN: installing antlir2-slowrolled version 1 (source /opt/chef-solo/bundle/cache/cookbooks/antlir2_test_chef_solo/recipes/slowroll_optional.rb:32:in `from_file')
[2024-07-16T21:50:32.183+00:00] WARN: ANTLIR2_CHEF_PLAN: antlir2-slowrolled-optional-provided-by-other-1 is not available, falling back on fast-snapshot (tag stable)
[2024-07-16T21:50:32.183+00:00] ERROR: ANTLIR2_CHEF_PLAN: Failed to plan chef run: undefined method `[]' for nil:NilClass
```

```name="With code change"
❯ buck2 test fbcode//antlir/antlir2/features/facebook/chef_solo/tests:test-slowroll-optional-cannot-be-installed
Buck UI: https://www.internalfb.com/buck2/f5b8881f-eaf3-4f3c-9287-535594473910
Test UI: https://www.internalfb.com/intern/testinfra/testrun/281475352204461
Network: Up: 0B  Down: 15MiB  (reSessionID-552fcc42-5e4d-455a-9593-0cc1f688c173)
Jobs completed: 32. Time elapsed: 1:41.7s.
Cache hits: 0%. Commands: 19 (cached: 0, remote: 0, local: 19)
Tests finished: Pass 1. Fail 0. Fatal 0. Skip 0. Build failure 0
```

Reviewed By: epilatow

Differential Revision: D59831702

fbshipit-source-id: f789f624441e069e05a70967f8cbe20027844fb4