Ignore decompressor exiting with SIGPIPE
Summary:
I added a test that used to fail -- failing to completely read a compressed stream would cause:

```
subprocess.CalledProcessError: Command '['gzip', '--decompress', '--stdout', b'/tmp/tmp3tu4rw3w/kitteh.gz']' died with <Signals.SIGPIPE: 13>.
```

In real life, we were seeing this as a **heisenbug** with `TarballItem.provides` ingesting a `.tgz` file:

Proposed root cause for the bug:
 - `gzip` is extracting a tarball to a pipe
 - Antlir python is reading from that pipe and interpreting it as a tarball
 - EITHER: `tar` encoding has fairly large padding at the end of an archive (like 10K of zeros IIRC)
 - OR: Antlir only needs the header of the last inode, and maybe `tarfile` is smart, and avoids reading the data of the last file.
 - In either case, we were likely not consuming the last few KB from the pipe, and in some cases, managing to close it before the decompressor had finished writing. This would tend to occur as a heisenbug under high I/O load, or when the last file was very large (if `tarfile` is smart).

I think ignoring `SIGPIPE` is a safe and reasonable approach here, but other options are available if people feel like this is a problem.

Reviewed By: zeroxoneb

Differential Revision: D25893138

fbshipit-source-id: 132627ba86efe7ea569c5725e98950583d9fd6ab