[antlir2][vm] check command exit status
Summary:
For interactive use cases, we don't care about command exit status.
For tpx test execution, it has its own way of reporting success and don't rely
on exit code. Thus we generally don't care about return status of the command.
Well, until I found out that sh_test's success is determined by its return
status...

So propagate command results up and surface the error only if we are running a
command. This would fix false negative for sh-tests, while not affecting
cpp/python/rust tests, as their test binary should always exit 0 and report
results in other ways.

Test Plan:
More complete unit tests. CI will cover existing tests and they
shouldn't fail (unless masked by this bug).

```name=fake an always failing sh test which passes without this diff and fails now
$ hg diff | pastry
P841873115: https://www.internalfb.com/intern/paste/P841873115/
$ buck test antlir/antlir2/antlir2_vm/tests:sh-test
✗ Fail: antlir/antlir2/antlir2_vm/tests:sh-test - main (43.2s)
Test returned with non-zero exit code
stdout:
2023-09-29T23:54:43.687904Z  INFO antlir2_vm::vm: Booting VM. It could take seconds to minutes...
2023-09-29T23:54:43.788603Z  INFO antlir2_vm::vm: Note: console output is redirected to /data/users/junjiew/fbsource/buck-out/v2/test/20230929-165119/ba618615-fdc1-4464-a421-4288e4e0a392/tpx_execution_dir/artifacts_directory/console.txt
2023-09-29T23:55:21.121398Z  INFO antlir2_vm::vm: Received boot event READY after 37.43299 seconds
2023-09-29T23:55:24.122193Z  INFO antlir2_vm::vm: VM executed for 40 seconds

stderr:
Pseudo-terminal will not be allocated because stdin is not a terminal. session=0e33a47e-4ea5-43c0-93a8-e9f2e3c1ff60:651763e9.234c6
Warning: Permanently added 'fe80::200:ff:fe00:1%vm0' (ED25519) to the list of known hosts. session=0e33a47e-4ea5-43c0-93a8-e9f2e3c1ff60:651763e9.234c6
+ exit 1
Error: SSH Command exited with error: exit status: 1
Error: VM run failed: ExitStatus(unix_wait_status(256))
Buck UI: https://www.internalfb.com/buck2/2d73693a-c648-4c2e-b34d-479a3868444d
Test UI: https://www.internalfb.com/intern/testinfra/testrun/17169973583664197
Network: Up: 460MiB  Down: 3.7GiB  (reSessionID-ac55ea34-a39a-49bd-9d7a-dcc1211c6c8d)
Jobs completed: 132. Time elapsed: 4:06.7s.
Cache hits: 0%. Commands: 89 (cached: 0, remote: 3, local: 86)
Tests finished: Pass 0. Fail 1. Fatal 0. Skip 0. Build failure 0
1 TESTS FAILED
  ✗ antlir/antlir2/antlir2_vm/tests:sh-test - main
```

```name=verify cpp/python/rust failures aren't turning into fatals
$ hg diff | pastry
P841881737: https://www.internalfb.com/intern/paste/P841881737/
$ buck test antlir/antlir2/antlir2_vm/tests:cpp-test antlir/antlir2/antlir2_vm/tests:python-test antlir/antlir2/antlir2_vm/tests:rust-test
Buck UI: https://www.internalfb.com/buck2/8eff3d17-038a-41db-a0c4-26678fb967cc
Test UI: https://www.internalfb.com/intern/testinfra/testrun/3940649876226143
Network: Up: 35KiB  Down: 251KiB  (reSessionID-d4eeb9cc-ed45-4cd0-a050-52f01b51fada)
Jobs completed: 181. Time elapsed: 55.9s.
Cache hits: 91%. Commands: 43 (cached: 39, remote: 1, local: 3)
Tests finished: Pass 3. Fail 3. Fatal 0. Skip 0. Build failure 0
3 TESTS FAILED
  ✗ antlir/antlir2/antlir2_vm/tests:rust-test - is_root
  ✗ antlir/antlir2/antlir2_vm/tests:python-test - test_is_root (antlir.antlir2.antlir2_vm.tests.test.TestInstalledBinary)
  ✗ antlir/antlir2/antlir2_vm/tests:cpp-test - CppTest.TestIsRoot
```

```name=start default VM and verify we aren't crashing vm on error exit
$ buck run antlir/antlir2/antlir2_vm:default-nondisk-boot
Buck UI: https://www.internalfb.com/buck2/5c5354ad-4715-4c26-9d6d-98b096fcc35a
Network: Up: 0B  Down: 0B
Jobs completed: 15. Time elapsed: 0.6s.
BUILD SUCCEEDED
2023-09-30T00:03:34.701963Z  INFO antlir2_vm::vm: Booting VM. It could take seconds to minutes...
2023-09-30T00:03:34.802646Z  INFO antlir2_vm::vm: Note: console output is redirected to /tmp/.tmpPHgfwr/console.txt
2023-09-30T00:04:26.801626Z  INFO antlir2_vm::vm: Received boot event READY after 52.099155 seconds
Warning: Permanently added 'fe80::200:ff:fe00:1%vm0' (ED25519) to the list of known hosts. session=8249abed-d734-4afc-8e0e-624012289eaa:6517660a.d5aa3
+======================================+
| ___  ___     _        _ _____ _____  |
| |  \/  |    | |      | |  _  /  ___| |
| | .  . | ___| |_ __ _| | | | \ `--.  |
| | |\/| |/ _ \ __/ _` | | | | |`--. \ |
| | |  | |  __/ || (_| | \ \_/ /\__/ / |
| \_|  |_/\___|\__\__,_|_|\___/\____/  |
|                                      |
+======================================+
[root@vmtest ~]# exit 1
logout
Connection to fe80::200:ff:fe00:1%vm0 closed.
2023-09-30T00:04:37.803386Z  INFO antlir2_vm::vm: VM executed for 63 seconds
```

Differential Revision: D49796161

fbshipit-source-id: 84b8b31abd666e9b409dbe0fc4ab0ea992d61327