[antlir2][vm] add missing log_command
Summary:
It's hard to understand what "Error: No such file or directory (os
error 2)" is referring to without knowing the command. Accidentally find this
during image testing.

Test Plan:
run locally with D45009191
```
$ RUST_LOG=trace buck run antlir/antlir2/antlir2_vm:antlir2_vm -- isolate --image /data/users/junjiew/fbsource/buck-out/v2/gen/fbcode/3f794b0267173c8e/antlir/antlir2/antlir2_vm/__container-image__/subvol-compile --vm-spec /tmp/vmopts.json --runtime /tmp/runtime.json
...
2023-05-31T22:33:30.496500Z DEBUG antlir2_vm: Args: Args { inner: ["/data/users/junjiew/fbsource/buck-out/v2/gen/fbcode/3f794b0267173c8e/antlir/antlir2/antlir2_vm/__antlir2_vm__/shared/antlir2_vm", "run", "--vm-spec", "/tmp/vmopts.json", "--runtime", "/tmp/runtime.json"] }
2023-05-31T22:33:30.497941Z TRACE antlir2_vm::utils: Executing command: systemd-detect-virt
Error: No such file or directory (os error 2)
...
```

Reviewed By: vmagro

Differential Revision: D46338518

fbshipit-source-id: 9473ae9198dfec508b8b8526bf0c0425b800519c