[third-party/rust] Replace unmaintained loopdev crate with loopdev-erikh fork
Summary:
Loopdev depends on an old version of bindgen (0.59) which is incompatible with LLVM 16+ due to not containing [rust-bindgen#2319](https://github.com/rust-lang/rust-bindgen/pull/2319), which is in bindgen 0.62.

This diff switches to a fork which is forked from upstream's master branch and uses bindgen 0.63. The fork contains only the following changes beyond what has already been merged into loopdev (but never released) by the loopdev maintainer.

```
diff loopdev/Cargo.toml loopdev-erikh/Cargo.toml.orig
2c2
< name = "loopdev"
 ---
> name = "loopdev-erikh"
5c5
< authors = ["Michael Daffin <michael@daffin.io>"]
 ---
> authors = ["Erik Hollensbe <erik@hollensbe.org>", "Michael Daffin <michael@daffin.io>"]
7,8c7,8
< documentation = "https://docs.rs/loopdev"
< repository = "https://github.com/mdaffin/loopdev"
 ---
> documentation = "https://docs.rs/loopdev-erikh"
> repository = "https://github.com/erikh/loopdev"
13,15d12
< [badges]
< build = { status = "https://github.com/mdaffin/loopdev/actions/workflows/ci.yml/badge.svg" }
<
20,21c17,18
< errno = "0.2.8"
< libc = "0.2.105"
 ---
> errno = "^0.2"
> libc = "^0.2"
24c21
< bindgen = { version = "0.63.0", default-features = false, features = ["runtime"] }
 ---
> bindgen = { version = "^0.63", default-features = false, features = ["runtime"] }
27,32c24,29
< glob = "0.3.0"
< gpt = "3.0.0"
< lazy_static = "1.4.0"
< serde = { version = "1.0.130", features = ["derive"] }
< serde_json = "1.0.68"
< tempfile = "3.2.0"
 ---
> glob = "^0.3"
> gpt = "^3"
> lazy_static = "^1.4"
> serde = { version = "^1", features = ["derive"] }
> serde_json = "^1"
> tempfile = "^3"

diff loopdev/LICENSE loopdev-erikh/LICENSE
2a3
> Copyright (c) 2023 Erik Hollensbe
```

Test Plan:
- `$ common/rust/tools/scripts/third-party-check.sh`

 ---

- `$ buck2 build fbsource//third-party/rust:loopdev` (with and without LLVM staging)

To obtain LLVM staging:

- `$ hg graft -r remote/scratch/server-llvm/staging -t :other`

**Before:** works only on LLVM 15. LLVM 18:

```
Action failed: fbsource//third-party/rust:loopdev-0.4.0-build-script-run (buildscript)

thread 'main' panicked at '"enum_(unnamed_at_/usr/include/linux/loop_h_21_1)" is not a valid Ident', third-party/rust/vendor/bindgen-0.59.2/src/ir/context.rs:878:9
stack backtrace:
   0: rust_begin_unwind
             at /home/engshare/third-party2/rust/1.72.1+llvm.15/src/build-platform010/build/rustc-1.72.1-src/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /home/engshare/third-party2/rust/1.72.1+llvm.15/src/build-platform010/build/rustc-1.72.1-src/library/core/src/panicking.rs:67:14
   2: validate_ident
             at ./third-party/rust/vendor/proc-macro2-1.0.70/src/fallback.rs:828:9
   3: <proc_macro2::fallback::Ident>::new_checked
             at ./third-party/rust/vendor/proc-macro2-1.0.70/src/fallback.rs:760:9
   4: <proc_macro2::imp::Ident>::new_checked
             at ./third-party/rust/vendor/proc-macro2-1.0.70/src/wrapper.rs:646:50
   5: <proc_macro2::Ident>::new
             at ./third-party/rust/vendor/proc-macro2-1.0.70/src/lib.rs:955:21
   6: <bindgen::ir::context::BindgenContext>::rust_ident_raw::<alloc::borrow::Cow<str>>
             at ./third-party/rust/vendor/bindgen-0.59.2/src/ir/context.rs:878:9
   7: <bindgen::ir::context::BindgenContext>::rust_ident::<&alloc::string::String>
             at ./third-party/rust/vendor/bindgen-0.59.2/src/ir/context.rs:870:9
   8: codegen
             at ./third-party/rust/vendor/bindgen-0.59.2/src/codegen/mod.rs:2907:21
   9: codegen
             at ./third-party/rust/vendor/bindgen-0.59.2/src/codegen/mod.rs:1004:39
  10: codegen
             at ./third-party/rust/vendor/bindgen-0.59.2/src/codegen/mod.rs:492:17
  11: <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen::{closure#0}
             at ./third-party/rust/vendor/bindgen-0.59.2/src/codegen/mod.rs:515:21
  12: codegen
             at ./third-party/rust/vendor/bindgen-0.59.2/src/codegen/mod.rs:545:13
  13: codegen
             at ./third-party/rust/vendor/bindgen-0.59.2/src/codegen/mod.rs:483:17
  14: {closure#0}
             at ./third-party/rust/vendor/bindgen-0.59.2/src/codegen/mod.rs:4287:9
  15: <bindgen::ir::context::BindgenContext>::gen::<bindgen::codegen::codegen::{closure#0}, alloc::vec::Vec<proc_macro2::TokenStream>>
             at ./third-party/rust/vendor/bindgen-0.59.2/src/ir/context.rs:1190:19
  16: bindgen::codegen::codegen
             at ./third-party/rust/vendor/bindgen-0.59.2/src/codegen/mod.rs:4251:5
  17: generate
             at ./third-party/rust/vendor/bindgen-0.59.2/src/lib.rs:2374:32
  18: <bindgen::Builder>::generate
             at ./third-party/rust/vendor/bindgen-0.59.2/src/lib.rs:1478:9
  19: build_script_build::main
             at ./third-party/rust/vendor/loopdev-0.4.0/build.rs:7:20
  20: <fn() as core::ops::function::FnOnce<()>>::call_once
             at /home/engshare/third-party2/rust/1.72.1+llvm.15/src/build-platform010/build/rustc-1.72.1-src/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**After:** works on both 15 and staging (LLVM 18).

 ---

- `$ fbgs loopdev::`

```
fbsource/fbcode/antlir/antlir2/antlir2_packager/btrfs_packager/src/main.rs:29:5:use loopdev::LoopControl;
fbsource/fbcode/antlir/antlir2/antlir2_packager/btrfs_packager/src/main.rs:30:5:use loopdev::LoopDevice;
fbsource/fbcode/antlir/antlir2/testing/image_test/src/main.rs:33:5:use loopdev::LoopControl;
fbsource/fbcode/metalos/lib/facebook/diagnostics/src/command.rs:8:5:use loopdev::LoopControl;
```

- `$ buck2 build fbcode//antlir/antlir2/antlir2_packager/btrfs_packager: fbcode//antlir/antlir2/testing/image_test: fbcode//metalos/lib/facebook/diagnostics:`

Reviewed By: zertosh

Differential Revision: D51636912

fbshipit-source-id: cbea00fa85582b479cb1af1df4480d93342f190a