[antlir2][vm] poll VM process for early failure
Summary:
I accidentally passed in wrong parameter for qemu and it exited
immediately. Currently we would continue to wait for the socket file that will
never appear. Fail faster by polling for unexpected process exit before socket
file shows up.

Test Plan:
Add unit test.

```name=Introduce failure (Note the bogus -whatever argument to qemu). With D44926488 V0.8.
$ RUST_LOG=trace buck run antlir/antlir2/antlir2_vm:default
2023-07-03T21:29:58.345951Z TRACE antlir2_vm::utils: Executing command: fbcode/third-party-buck/platform010/build/qemu/bin/qemu-system-x86_64 -whatever -no-reboot -display none -serial mon:stdio -cpu host -smp 1 -m 4096M -object rng-random,filename=/dev/urandom,id=rng0 -device virtio-rng-pci,rng=rng0 -device virtio-serial -chardev socket,path=/run/vm_state/vmtest_notify.sock,id=notify,server=on -device virtserialport,chardev=notify,name=notify-host -drive if=pflash,format=raw,unit=0,file=buck-out/v2/gen/fbcode/67e0758f7bdffa6c/antlir/vm/runtime/__edk2-x86_64-code.fd__/out/out,readonly=on -L buck-out/v2/gen/fbcode/67e0758f7bdffa6c/antlir/vm/runtime/__roms__/out -enable-kvm -blockdev driver=qcow2,node-name=vd0,file.driver=file,file.filename=/run/vm_state/vd0.qcow2 -device virtio-blk,drive=vd0,serial=vd0,physical_block_size=512,logical_block_size=512 -chardev socket,id=fs_chardev0,path=/run/vm_state/fs0 -device vhost-user-fs-pci,queue-size=1024,chardev=fs_chardev0,tag=fs0 -chardev socket,id=fs_chardev1,path=/run/vm_state/fs1 -device vhost-user-fs-pci,queue-size=1024,chardev=fs_chardev1,tag=fs1 -chardev socket,id=fs_chardev2,path=/run/vm_state/fs2 -device vhost-user-fs-pci,queue-size=1024,chardev=fs_chardev2,tag=fs2 -virtfs local,path=/run/vm_state/mount_units,security_model=none,multidevs=remap,mount_tag=exports,readonly=on -object memory-backend-memfd,id=mem,share=on,size=4096M -numa node,memdev=mem -netdev tap,id=net0,ifname=vm0,script=no,downscript=no -device virtio-net-pci,netdev=net0,mac=00:00:00:00:00:01
2023-07-03T21:29:58.346347Z DEBUG antlir2_vm::vm: Waiting for notify file to be created
Error: Failed to boot VM: `VM process exited prematurely: exit status: 1`
```

```name=Make sure VM still boots fine with D45009191 V0.6 (D44926488 not fully ready yet).
$ buck run antlir/antlir2/antlir2_vm:hack
$ buck run antlir/antlir2/antlir2_vm:antlir2_vm -- isolate --image /data/users/junjiew/fbsource/buck-out/v2/gen/fbcode/67e0758f7bdffa6c/antlir/antlir2/antlir2_vm/__container-image__/subvol-compile_compile --vm-spec /tmp/vmopts.json --runtime /tmp/runtime.json
Last login: Mon Jul  3 14:37:50 2023
+======================================+
| ___  ___     _        _ _____ _____  |
| |  \/  |    | |      | |  _  /  ___| |
| | .  . | ___| |_ __ _| | | | \ `--.  |
| | |\/| |/ _ \ __/ _` | | | | |`--. \ |
| | |  | |  __/ || (_| | \ \_/ /\__/ / |
| \_|  |_/\___|\__\__,_|_|\___/\____/  |
|                                      |
+======================================+
[root@vmtest ~]# exit
logout
```

Differential Revision: D47198997

fbshipit-source-id: dd2b563ecd28e4ac15d08e04db680b72c4305bff