msys: cql: Use BUCK_SCRATCH_DIR instead of /tmp for argsfiles
Summary:
We're onboarding cathode to TEE builds (which use a special toolchain that's quite different from the standard fbcode toolchain).

Among other things, the compiler is invoked inside a separate container environment. When this binary writes argsfiles, today it writes them to /tmp which isnt' visible to the compiler container and the invocation fails.

Instead, we can write these to `$BUCK_SCRATCH_DIR`, a variable pointing to a buck-managed scratch directory that's always available (in RE or locally) and cleaned up after each action.

If for some reason this isn't set, we'll fall back to writing into /tmp

Before this diff:
```
$ buck2 build fbcode//mode/opt fbcode//mode/tee fbcode//cathode/usecases/tee_wa_rtc_genai_bot:__cvm_worker
Action failed: fbsource//xplat/msys:msysInfraReaders_142253225_b_outs (genrule)
Remote command returned non-zero exit code 1
Reproduce locally: `frecli cas download-action edd7bdb547cb50644243cd3bfaed3036994cf9390b8133214d8ac995ea09051a:145`
stdout:
stderr:
2025-08-08T06:15:59.420764Z TRACE unshare_new_userns: antlir2_rootless: looking up best subid ranges for 30083 (fbnobody)
2025-08-08T06:15:59.420831Z TRACE unshare_new_userns: antlir2_rootless: using uid range Range { start: Uid(493216), len: IdOffset(65536) } and gid range Range { start: Gid(493216), len: IdOffset(65536) }
clang: error: no such file or directory: '@/re_tmp/tmpnmoploez'
clang: error: no input files
Error: command failed

Bundle: //xplat/msys:msysInfraReaders_142253225_b
Command: buck-out/v2/gen/fbcode/c3471beab0b154f0/antlir/distro/toolchain/cxx/__toolchain--actual--centos9--clang__/script.sh  @/re_tmp/tmpnmoploez

==> There was an error running the preprocessor on your CQL code.
    There is likely some error in the way that your BUCK dependencies
    are set up and some #include path could not be figured out.
    Please fix those and rerun your command.
Buck UI: https://www.internalfb.com/buck2/fc7616e3-1fcc-472e-bbc8-36c1ef8b5fe9
Network: Up: 6.8MiB  Down: 37MiB  (reSessionID-ea6b936c-3e78-49bd-bae5-b3558ed7b184)
Executing actions. Remaining     0/8514                                                                                                       39:33.3s exec time total
Command: build.    Finished 79 local, 147 remote, 893 cache (80% hit)                                                                         35:22.3s exec time cached (89%)
Time elapsed: 5.4s
BUILD FAILED
Failed to build 'fbsource//xplat/msys:msysInfraReaders_142253225_b_outs (cfg:opt-linux-x86_64-clang19-no-san#c0148ff2ffa75fc2)'
```

Test Plan:
Build a rule invoking this binary with fbcode//mode/tee, it gets past the failing msys rule but fails on something else (future work):
```
$ buck2 build fbcode//mode/opt fbcode//mode/tee fbcode//cathode/usecases/tee_wa_rtc_genai_bot:__cvm_worker
File changed: fbcode//antlir/distro/toolchain/cxx/defs.bzl
File changed: fbsource//xplat/msys/tools/cql/build_defs/cql_bundle_output_creator.py
Action failed: fbcode//cathode/experimental/duplex_bot_module/prewarm:factory (cxx_compile DefaultComponentFactory.cpp)
Remote command returned non-zero exit code 1
Reproduce locally: `frecli cas download-action 2459c89cdc8a185bfc50d09901eb055985ea12e26e6e1bade61fdb99a8510e08:145`
stdout:
stderr:
2025-08-08T06:18:18.331092Z TRACE unshare_new_userns: antlir2_rootless: looking up best subid ranges for 30083 (fbnobody)
2025-08-08T06:18:18.331151Z TRACE unshare_new_userns: antlir2_rootless: using uid range Range { start: Uid(493216), len: IdOffset(65536) } and gid range Range { start: Gid(493216), len: IdOffset(65536) }
In file included from fbcode/cathode/experimental/duplex_bot_module/prewarm/DefaultComponentFactory.cpp:3:
In file included from buck-out/v2/gen/fbcode/c0148ff2ffa75fc2/cathode/experimental/duplex_bot_module/prewarm/__factory__/buck-headers/cathode/experimental/duplex_bot_module/prewarm/DefaultComponentFactory.h:5:
buck-out/v2/gen/fbcode/c0148ff2ffa75fc2/cathode/experimental/duplex_bot_module/prewarm/__factory__/buck-headers/cathode/experimental/duplex_bot_module/prewarm/ComponentFactory.h:8:10: fatal error: 'langtech/mobile/audio_stream_processor/AudioStreamProcessor.h' file not found
    8 | #include "langtech/mobile/audio_stream_processor/AudioStreamProcessor.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Error: command failed
Buck UI: https://www.internalfb.com/buck2/94d975a1-2e07-484c-896c-4cc805608a07
Network: Up: 14MiB  Down: 18MiB  (reSessionID-4dc00797-d82d-479d-bc29-b08669d0a415)
Loading targets.   Remaining     0/1                                                                                                          1 dirs read, 56 targets declared
Analyzing targets. Remaining     0/9980                                                                                                       226810 actions, 229435 artifacts declared
Executing actions. Remaining     0/45474                                                                                                      2:17:14.1s exec time total
Command: build.    Finished 431 local, 3806 remote
Time elapsed: 31.5s
BUILD FAILED
Failed to build 'fbcode//cathode/experimental/duplex_bot_module/prewarm:factory (cfg:opt-linux-x86_64-clang19-no-san#c0148ff2ffa75fc2)'
```

Rollback Plan:

Reviewed By: egpast, vmagro

Differential Revision: D79868681

fbshipit-source-id: 933a84a9b89b85690b561191d68068bfeb778a20