[antlir2][rpms] don't silently remove explicitly installed package
Summary:
RPMs in an image come in two classes that we care about:
1) explicitly user-installed (with `feature.rpms_install`)
2) dependencies of the above

RPMS in class #1 should be protected at all costs. The image API is designed to
be very explicit, we don't want things to unexpectedly change out from under
the author. To accomplish this we refuse to complete any dnf transaction that
_implicitly_ removes any of these packages.
To remove a user-installed package, one must use
`feature.rpms_remove(_if_exists)`.

Note that this is slightly different from antlir1 (that accomplishes _similar_
but not quite _identical_ functionality via
`dnf-plugin-flunk_dependent_remove`) in that transitively installed rpms (class
#2 above) _can_ be removed implicitly in a transaction that removes the rpm
that originally pulled the transitively-removed package in as a dependency, but
this is desirable since the user never asked for those RPMs in the first place.

As a consequence of this, RPMs that are required for image operation must
always be explicitly installed - if they are only brought in as a dependency,
it may be transitively removed later if no longer required by any
user-installed rpms.

Test Plan:
Before updating the remove-test
```
❯ buck2 test fbcode//antlir/antlir2/test_images/rpms:remove-test
File changed: fbcode//antlir/antlir2/antlir2_compile/dnf-driver.py
Action failed: fbcode//antlir/antlir2/test_images/rpms:remove (antlir2_map plan)
Local command returned non-zero exit code 1
Reproduce locally: `env -- "RUST_LOG=antlir2=trace" sudo buck-out/v2/gen/fbcode/bb71128f9fe99274/antlir/antlir2/antlir2/ ...<omitted>... re" "--plan=buck-out/v2/gen/fbcode/e97a0788aa35bdc8/antlir/antlir2/test_images/rpms/__remove__/plan" (run `buck2 log what-failed` to get the full command)`
stdout:
D0427 07:38:43.264026 2690061 antlir/antlir2/antlir2/src/cmd/map.rs:137] [map, create_new_subvol{working_volume: WorkingVolume("antlir2-out")}] produced r/w subvol 'Subvolume { id: 22544, path: "/data/users/vmagro/fbsource/antlir2-out/1682606323-13dc4a48b2234ea29d4211eafd516523-fbcode--antlir-antlir2-test_images-rpms:remove-(ovr_config--platform-linux:x86_64-fbcode-platform010-clang#e97a0788aa35bdc8)-plan", info: SubvolumeInfo { id: 22544, parent_id: Some(5), dir_id: Some(137696645), flags: (empty), uuid: be621f55-cd8c-9a42-aee3-5e5da213192c, parent_uuid: Some(affa5a57-7b83-4145-98b8-ff61884576ba), received_uuid: None, generation: 810965, ctransid: 810965, otransid: 810965, stransid: None, rtransid: None } }'
I0427 07:38:43.264103 2690061 antlir/antlir2/antlir2/src/cmd/map.rs:101] [map, create_new_subvol{working_volume: WorkingVolume("antlir2-out")}] return: Subvolume { id: 22544, path: "/data/users/vmagro/fbsource/antlir2-out/1682606323-13dc4a48b2234ea29d4211eafd516523-fbcode--antlir-antlir2-test_images-rpms:remove-(ovr_config--platform-linux:x86_64-fbcode-platform010-clang#e97a0788aa35bdc8)-plan", info: SubvolumeInfo { id: 22544, parent_id: Some(5), dir_id: Some(137696645), flags: (empty), uuid: be621f55-cd8c-9a42-aee3-5e5da213192c, parent_uuid: Some(affa5a57-7b83-4145-98b8-ff61884576ba), received_uuid: None, generation: 810965, ctransid: 810965, otransid: 810965, stransid: None, rtransid: None } }
D0427 07:38:43.264981 2690061 antlir/antlir2/antlir2/src/cmd/map.rs:220] [map] isolated command: "sudo" "systemd-nspawn" "--quiet" "--directory" "buck-out/v2/gen/fbcode/e97a0788aa35bdc8/antlir/antlir2/facebook/images/build_appliance/__build-appliance.c9__/subvol_symlink" "--ephemeral" "--register=no" "--private-network" "--as-pid2" "--chdir" "/data/users/vmagro/fbsource" "--setenv" "RUST_LOG=antlir2=trace" "--bind-ro" "/data/users/vmagro/fbsource" "--bind-ro" "/mnt/gvfs" "--bind-ro" "/usr/local/fbcode" "--bind-ro" "/data/users/vmagro/fbsource" "--bind-ro" "/data/users/vmagro/fbsource/antlir2-out" "--bind-ro" "/data/users/vmagro/fbsource/buck-out/v2/gen/fbcode/e97a0788aa35bdc8/antlir/antlir2/test_images/rpms/__remove__/dnf_repodatas" "--bind" "/data/users/vmagro/fbsource/antlir2-out" "--bind" "/data/users/vmagro/fbsource/buck-out/v2/gen/fbcode/e97a0788aa35bdc8/antlir/antlir2/test_images/rpms/__remove__/plan" "--" "/data/users/vmagro/fbsource/buck-out/v2/gen/fbcode/bb71128f9fe99274/antlir/antlir2/antlir2/__antlir2__/shared/antlir2" "plan" "--label" "fbcode//antlir/antlir2/test_images/rpms:remove (ovr_config//platform/linux:x86_64-fbcode-platform010-clang#e97a0788aa35bdc8)" "--target-arch" "x86_64" "--depgraph-json" "buck-out/v2/gen/fbcode/e97a0788aa35bdc8/antlir/antlir2/test_images/rpms/__remove__/depgraph.json.pre" "--root" "/data/users/vmagro/fbsource/antlir2-out/1682606323-13dc4a48b2234ea29d4211eafd516523-fbcode--antlir-antlir2-test_images-rpms:remove-(ovr_config--platform-linux:x86_64-fbcode-platform010-clang#e97a0788aa35bdc8)-plan" "--dnf-repos" "buck-out/v2/gen/fbcode/e97a0788aa35bdc8/antlir/antlir2/test_images/rpms/__remove__/dnf_repodatas" "--dnf-versionlock" "buck-out/v2/gen/fbcode/e97a0788aa35bdc8/antlir/antlir2/facebook/flavor/__centos9--versionlock__/versionlock.json" "--plan" "buck-out/v2/gen/fbcode/e97a0788aa35bdc8/antlir/antlir2/test_images/rpms/__remove__/plan"
Traceback (most recent call last):
  File "/antlir/dnf-driver.py", line 298, in <module>
    main()
  File "/antlir/dnf-driver.py", line 283, in main
T0427 07:38:49.915650     2 antlir/antlir2/antlir2_compile/src/rpms.rs:188] [plan] dnf-driver: TransactionResolved { install: {}, remove: {Package { name: "foo", epoch: 0, version: "3", release: "1", arch: "noarch" }, Package { name: "foobar", epoch: 0, version: "3", release: "1", arch: "noarch" }, Package { name: "foobarbaz", epoch: 0, version: "3", release: "1", arch: "noarch" }} }
    raise RuntimeError(
RuntimeError: This transaction would remove some explicitly installed packages. Modify the image features to explicitly remove these packages: foobarbaz
dnf-driver.py failed
stderr:
"isolated command failed: exit status: 1"
Buck UI: https://www.internalfb.com/buck2/6f1c7b30-262c-4419-8aa7-7de6383077d6
Test UI: https://www.internalfb.com/intern/testinfra/testrun/5066549746485369
RE: reSessionID-35a63c03-bfee-4be3-a1c5-e1c5d2144584  Up: 16 MiB  Down: 0 B
Jobs completed: 89. Time elapsed: 46.6s. Cache hits: 0%. Commands: 68 (cached: 0, remote: 0, local: 68)
for action key `(target: `fbcode//antlir/antlir2/test_images/rpms:remove (ovr_config//platform/linux:x86_64-fbcode-platform010-clang#e97a0788aa35bdc8)`, id: `6`)`: Failed to build 'fbcode//antlir/antlir2/test_images/rpms:remove (ovr_config//platform/linux:x86_64-fbcode-platform010-clang#e97a0788aa35bdc8)'
1 BUILDS FAILED
Tests finished: Pass 0. Fail 0. Fatal 0. Skip 0. 1 builds failed
```

```
❯ buck2 test fbcode//antlir/antlir2/test_images/rpms:
```
https://www.internalfb.com/intern/testinfra/testrun/5629499701321388

Reviewed By: sergeyfd

Differential Revision: D45356544

fbshipit-source-id: 26c8e2b51bae703bb26313adbb4bc6cb6f40a8a2