vmtest: Manually specify runtime dependencies for final buck_sh_test target
Summary: - Need to make sure buck uploads all the test's runtime dependencies to remote execution

Test Plan:
# Before

```
[pdel@devgpu051.atn2 tests]# buck test :python-remote-execution -- --run-disabled
File changed: fbsource//.hgmonitor.status
File changed: fbcode//antlir/vm/bzl/defs.bzl
File changed: fbcode//antlir/vm/tests/TARGETS
 Listing failed: antlir/vm/tests:mpython-remote-execution
Failed to list tests.
STDOUT:
STDERR:./buck-out/v2/gen/fbcode/67e0758f7bdffa6c/antlir/vm/tests/__python-remote-execution_eqsb_vmtest__/out/out: line 9: /re_cwd/buck-out/v2/gen/fbcode/67e0758f7bdffa6c/antlir/vm/__vmtest__/vmtest.par: No such fi
le or directory

Buck UI: https://www.internalfb.com/buck2/cf9a409f-fe35-434b-bf74-fccb277bd75b
Test UI: https://www.internalfb.com/intern/testinfra/testrun/4503599808980529
Network: Up: 1.5 GiB  Down: 2.8 GiB  (reSessionID-cb285cbe-6aad-4051-bc74-3b4faeb39ab1)
Jobs completed: 151. Time elapsed: 5.0s.
Tests finished: Listing Fail 1. Pass 0. Fail 0. Fatal 0. Skip 0. Build failure 0
1 LISTINGS FAILED
   antlir/vm/tests:python-remote-execution
```

# After

```
Traceback (most recent call last):
  File "<string>", line 38, in <module>
  File "<string>", line 36, in __run
  File "/usr/local/fbcode/platform010/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/fbcode/platform010/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/re_cwd/buck-out/v2/gen/fbcode/67e0758f7bdffa6c/antlir/vm/__vmtest__/vmtest#link-tree/antlir/vm/vmtest.py", line 389, in <module>
    asyncio.run(run(**dict(VMTestExecOpts.parse_cli(sys.argv[1:]))))
  File "/usr/local/fbcode/platform010/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/fbcode/platform010/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/re_cwd/buck-out/v2/gen/fbcode/67e0758f7bdffa6c/antlir/vm/__vmtest__/vmtest#link-tree/antlir/vm/vmtest.py", line 302, in run
    async with vm(
  File "/usr/local/fbcode/platform010/lib/python3.8/contextlib.py", line 171, in __aenter__
    return await self.gen.__anext__()
  File "/re_cwd/buck-out/v2/gen/fbcode/67e0758f7bdffa6c/antlir/vm/__vmtest__/vmtest#link-tree/antlir/vm/common.py", line 38, in wrapper
    async with f(*args, stack=stack, **kwargs) as r:
  File "/usr/local/fbcode/platform010/lib/python3.8/contextlib.py", line 171, in __aenter__
    return await self.gen.__anext__()
  File "/re_cwd/buck-out/v2/gen/fbcode/67e0758f7bdffa6c/antlir/vm/__vmtest__/vmtest#link-tree/antlir/vm/vm.py", line 292, in vm
    disks = [
  File "/re_cwd/buck-out/v2/gen/fbcode/67e0758f7bdffa6c/antlir/vm/__vmtest__/vmtest#link-tree/antlir/vm/vm.py", line 293, in <listcomp>
    QCow2Disk(
  File "<string>", line 15, in __init__
  File "/re_cwd/buck-out/v2/gen/fbcode/67e0758f7bdffa6c/antlir/vm/__vmtest__/vmtest#link-tree/antlir/vm/share.py", line 264, in __post_init__
    _tmp_qcow2_disk(
  File "/re_cwd/buck-out/v2/gen/fbcode/67e0758f7bdffa6c/antlir/vm/__vmtest__/vmtest#link-tree/antlir/vm/share.py", line 200, in _tmp_qcow2_disk
    subprocess.run(["chattr", "+C", tmpdir], check=True)
  File "/usr/local/fbcode/platform010/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/fbcode/platform010/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executablx, preexec_fn, cls_e_fds,
  File "/usr/local/fbcode/platform010/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chattr'
```

Reviewed By: vmagro

Differential Revision: D46626692

fbshipit-source-id: 54eb542310f0ed31affc06058df2cc4f0d3cb559