remove cyrillic chars from comments
Summary:
This breaks parsing of bzl files on Windows.

I don't think this target will work on Windows but let just fix parsing at least.

Error message:
```
Buck wasn't able to parse C:\open\fbsource\fbcode\remote_execution\rust\command\TARGETS:
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 3528: character maps to <undefined>
Call stack:
  File "C:\open\fbsource\fbcode\buck-out\tmp\resources\d9c2eba7bf0bebb6da5063be26c2992b\buck_server\buck_parser\profiler.py", line 508, in wrapped
    return func(*args, **kwargs)
  File "C:\open\fbsource\fbcode\remote_execution\rust\command\TARGETS", line 7
    load("//tupperware/sudotest:defs.bzl", "sudo_rust_unittest")
  File "C:\open\fbsource\fbcode\buck-out\tmp\resources\d9c2eba7bf0bebb6da5063be26c2992b\buck_server\buck_parser\profiler.py", line 508, in wrapped
    return func(*args, **kwargs)
  File "C:\open\fbsource\fbcode\tupperware\sudotest\defs.bzl", line 9
    image_test_helpers = "image_unittest_helpers",
  File "C:\open\fbsource\fbcode\buck-out\tmp\resources\d9c2eba7bf0bebb6da5063be26c2992b\buck_server\buck_parser\profiler.py", line 508, in wrapped
  File "C:\open\fbsource\fbcode\antlir\bzl\image_unittest_helpers.bzl", line 1
    load("//antlir/bzl/image_actions:install.bzl", "image_install_buck_runnable")
    return func(*args, **kwargs)
  File "C:\open\fbsource\fbcode\antlir\bzl\image_actions\install.bzl", line 55
    load("//antlir/bzl:target_tagger.bzl", "extract_tagged_target", "image_source_as_target_tagged_dict", "new_target_tagger", "tag_and_maybe_wrap_executable_target", "target_tagger_to_feature")
  File "C:\open\fbsource\fbcode\buck-out\tmp\resources\d9c2eba7bf0bebb6da5063be26c2992b\buck_server\buck_parser\profiler.py", line 508, in wrapped
    return func(*args, **kwargs)
  File "C:\open\fbsource\fbcode\antlir\bzl\target_tagger.bzl", line 25
    load(":wrap_runtime_deps.bzl", "maybe_wrap_executable_target")
  File "C:\open\fbsource\fbcode\buck-out\tmp\resources\d9c2eba7bf0bebb6da5063be26c2992b\buck_server\buck_parser\profiler.py", line 508, in wrapped
    return func(*args, **kwargs)
  File "C:\open\fbsource\fbcode\antlir\bzl\wrap_runtime_deps.bzl", line 2
    load(":constants.bzl", "REPO_CFG")
  File "C:\open\fbsource\fbcode\buck-out\tmp\resources\d9c2eba7bf0bebb6da5063be26c2992b\buck_server\buck_parser\profiler.py", line 508, in wrapped
    return func(*args, **kwargs)
  File "C:\Python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]

This error happened while trying to get dependency '//remote_execution/rust/command:command' of target '//remote_execution/rust/worker:main'
```

Reviewed By: justintrudell

Differential Revision: D25423346

fbshipit-source-id: 895816a0db088cc994eded220a826c73ef4524a7