Fix failing rpm-replay test
Summary:
Fixes the test introduced in D29408374 (https://github.com/facebookincubator/antlir/commit/0a5a4e1e9e09bdc336593aaf52b9897e471f1d9c) which was failing in CI when tested with `mode/opt` with error

```
======================================================================
FAIL: test_replay_rpms_and_compiler_items (antlir.rpm.replay.tests.test_rpm_replay.RpmReplayTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dev/shm/uid-0/e8c3e6a0-seed-nspid4026533450_cgpid3878246-ns-4026533449/antlir/rpm/replay/tests/test_rpm_replay.py", line 75, in test_replay_rpms_and_compiler_items
    self.assertEqual(diff, [])
AssertionError: Lists differ: [b'.meta/private/opts/artifacts_may_require_repo'] != []
```

Reviewed By: zeroxoneb

Differential Revision: D29526525

fbshipit-source-id: 437df7418cf3b0068072c446020598f637ebac5b