- make /run/fs/control/run/state/metalos visible to metald
Summary:
I faced a small bug when testing metald only as Native Service
```
➜  fbcode buck2 run //metalos/metald/facebook/cli:metald_cli -- --hostname rsw1cz.21.frc3.facebook.com --port 32123 online-update-stage
....
Error: Encountered error: e(UpdateStageError { packages: [], message: "while staging runtimeconfig: while save config to disk\n\nCaused by:\n    0: while serializing to /run/fs/control/run/state/metalos/metalos_host_configs::runtime_config::RuntimeConfig-cdad3678d6ab45cfb77d283c180025682fafbfbb7bdd3b890789ba8a5d190c1c.json\n    1: No such file or directory (os error 2)" })
```
Adding this with a dropin seems solving the problem.
**BindPaths=/run/fs/control/run/state/metalos**

Need to check with **metalos** folks if this is the correct approach

Reviewed By: vmagro

Differential Revision: D38616669

fbshipit-source-id: 10d4687859b5c5810191c6bbdba28b54b2618c85