extract.extract outputs feature.json instead of blanket image.clone
Summary:
When I tried to add an `extract.extract` feature to a layer I was blocked by error:
```
RuntimeError: ItemProv(provides=ProvidesDirectory(req=RequireDirectory(kind=<RequirementKind.PATH: 1>, path=b'/usr')), item=PhasesProvideItem(from_target='//antlir/linux/initrd/vmtest:5.2.9-229_fbk15_hardened_4185_g357f49b36602-initrd-debug--layer', subvol=<antlir.subvol_utils.Subvol object at 0x7fe4e1f91c70>)) conflicts with ItemProv(provides=ProvidesDirectory(req=RequireDirectory(kind=<RequirementKind.PATH: 1>, path=b'/usr')), item=CloneItem(dest=b'', omit_outer_dir=True, pre_existing_dest=True, source=b'/data/users/qingyuch/fbsource/fbcode/buck-image-out/volume/targets/image-extract-work---p1I-JUAzIkq3iGjDbTdV2hIYg6jcS6nRGQawaKqvak:JfIp3Tc.ARpI.6S06/volume/output', source_layer=<antlir.subvol_utils.Subvol object at 0x7fe4e1fafca0>))
```
Because the extract feature provides `/usr` which is already provided by the parent layer.
And that's because the extract feature was essentially a blanket `clone` action which copies everything from the `/output` directory in extract work layer to the new layer. However in Antlir compiler this `CloneItem` conflicts with the existing PhasesProvideItem.

This diff tries to solve this problem by replacing the blanket `clone` action in extract.extract, with a genrule that generates a `feature.json` directly for the compiler to consume. This `feature.json` will only include `clone` actions for leaf files and `ensure_subdirs_exist` actions for directories. This now works because unlike `CloneItem`, multiple `EnsureDirsExistItem` are allowed.

Reviewed By: zeroxoneb

Differential Revision: D30674008

fbshipit-source-id: c8dd17192ed5158608addb161d8a9c164a78fad8