[antlir2][vm] add missing label for python tests
Summary:
Some tests aren't happy with our existing labels for python tests,
even though it worked fine for some. Copy more magic from
antlir/vm/bzl/defs.bzl for the labels.
```
$ buck targets resctl/atropos/vm_tests:
File changed: fbcode//antlir/antlir2/antlir2_vm/bzl/test.bzl
Error parsing fbcode//resctl/atropos/vm_tests
Error evaluating build file: `fbcode//resctl/atropos/vm_tests:TARGETS`

Caused by:
    Traceback (most recent call last):
      * fbcode/resctl/atropos/vm_tests/TARGETS:25, in <module>
          vm.python_test(
      * fbcode/buck2/starlark-rust/starlark/src/stdlib/partial.rs:175, in partial
          <native>
      * fbcode/antlir/antlir2/antlir2_vm/bzl/test.bzl:141, in _implicit_vm_test
          test_rule(
      * fbcode/antlir/bzl/build_defs.bzl:174, in python_unittest
          shim.python_unittest(**kwargs)
      * fbcode/antlir/bzl/build_defs_impl.bzl:404, in _python_unittest
          _wrap_internal(python_unittest, args, kwargs)
      * fbcode/antlir/bzl/build_defs_impl.bzl:298, in _wrap_internal
          fn(*args, **kwargs)
      * tools/build_defs/fbcode_macros/build_defs/python_unittest.bzl:257, in python_unittest
          fail(
    error: fail: You are trying to run a new TestPilot adapter interface module but is not using the tag 'use-testpilot-adapter' to enable that.
       --> tools/build_defs/fbcode_macros/build_defs/python_unittest.bzl:257:13
        |
    257 |               fail(
        |  _____________^
    258 | |                 "You are trying to run a new TestPilot adapter interface module but " +
    259 | |                 "is not using the tag 'use-testpilot-adapter' to enable that.",
    260 | |             )
        | |_____________^
        |

Failed to parse 1 package
```

Test Plan: CI

Reviewed By: vmagro

Differential Revision: D49440968

fbshipit-source-id: a124d53bd10b1ca292cdb7b05576262e44d7c50e