tee: Add abseil-cpp dep on re2
Summary:
When building for centos10, the orchestrator build fails because re2 tries to include some abseil-cpp headers:
```
$ buck build --flagfile fbcode//mode/dev fbcode//tee/snp/image/examples/sidecar/centos10/cvm_fbpkg:tee.snp.tw.cvm.sidecar_example.c10__hash_tree__extract_rootfs
Action failed: fbcode//tee/tee_routing_service/client_routing:utils (cxx_compile Utils.cpp (pic))
Local command returned non-zero exit code 1
Reproduce locally: `env -- 'BUCK_SCRATCH_PATH=buck-out/v2/tmp/fbcode/c259e7b336159f44/cxx_compile/_buck_78ba2b20faf28aad ...<omitted>... uting/__utils__/.cpp.cxx_compile_argsfile -c fbcode/tee/tee_routing_service/client_routing/Utils.cpp (run `buck2 log what-failed` to get the full command)`
stdout:
stderr:
2025-06-24T17:03:47.456053Z TRACE unshare_new_userns: antlir2_rootless: looking up best subid ranges for 32133 (skarlage)
2025-06-24T17:03:47.456115Z TRACE unshare_new_userns: antlir2_rootless: using uid range Range { start: Uid(1879048192), len: IdOffset(65536) } and gid range Range { start: Gid(1879048192), len: IdOffset(65536) }
In file included from fbcode/tee/tee_routing_service/client_routing/Utils.cpp:3:
In file included from buck-out/v2/gen/fbcode/0d02068896024821/tee/tee_routing_service/client_routing/__utils__/buck-headers/tee/tee_routing_service/client_routing/Utils.h:5:
buck-out/v2/gen/fbcode/0d02068896024821/folly/ssl/__openssl_ptr_types__/buck-headers/folly/ssl/OpenSSLPtrTypes.h:95:53: warning: 'HMAC_CTX_free' is deprecated [-Wdeprecated-declarations]
   95 | FOLLY_SSL_DETAIL_DEFINE_PTR_TYPE(HmacCtx, HMAC_CTX, HMAC_CTX_free);
      |                                                     ^
buck-out/v2/gen/fbcode/0d02068896024821/antlir/distro/deps/openssl/__ssl--outputs__/outs/headers/openssl/hmac.h:35:1: note: 'HMAC_CTX_free' has been explicitly marked deprecated here
   35 | OSSL_DEPRECATEDIN_3_0 void HMAC_CTX_free(HMAC_CTX *ctx);
      | ^
buck-out/v2/gen/fbcode/0d02068896024821/antlir/distro/deps/openssl/__ssl--outputs__/outs/headers/openssl/macros.h:217:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
  217 | #   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
      |                                                 ^
buck-out/v2/gen/fbcode/0d02068896024821/antlir/distro/deps/openssl/__ssl--outputs__/outs/headers/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
   62 | #     define OSSL_DEPRECATED(since) __attribute__((deprecated))
      |                                                    ^
In file included from fbcode/tee/tee_routing_service/client_routing/Utils.cpp:3:
In file included from buck-out/v2/gen/fbcode/0d02068896024821/tee/tee_routing_service/client_routing/__utils__/buck-headers/tee/tee_routing_service/client_routing/Utils.h:5:
buck-out/v2/gen/fbcode/0d02068896024821/folly/ssl/__openssl_ptr_types__/buck-headers/folly/ssl/OpenSSLPtrTypes.h:108:44: warning: 'RSA_free' is deprecated [-Wdeprecated-declarations]
  108 | FOLLY_SSL_DETAIL_DEFINE_PTR_TYPE(Rsa, RSA, RSA_free);
      |                                            ^
buck-out/v2/gen/fbcode/0d02068896024821/antlir/distro/deps/openssl/__ssl--outputs__/outs/headers/openssl/rsa.h:304:1: note: 'RSA_free' has been explicitly marked deprecated here
  304 | OSSL_DEPRECATEDIN_3_0 void RSA_free(RSA *r);
      | ^
buck-out/v2/gen/fbcode/0d02068896024821/antlir/distro/deps/openssl/__ssl--outputs__/outs/headers/openssl/macros.h:217:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
  217 | #   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
      |                                                 ^
buck-out/v2/gen/fbcode/0d02068896024821/antlir/distro/deps/openssl/__ssl--outputs__/outs/headers/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
   62 | #     define OSSL_DEPRECATED(since) __attribute__((deprecated))
      |                                                    ^
In file included from fbcode/tee/tee_routing_service/client_routing/Utils.cpp:3:
In file included from buck-out/v2/gen/fbcode/0d02068896024821/tee/tee_routing_service/client_routing/__utils__/buck-headers/tee/tee_routing_service/client_routing/Utils.h:5:
buck-out/v2/gen/fbcode/0d02068896024821/folly/ssl/__openssl_ptr_types__/buck-headers/folly/ssl/OpenSSLPtrTypes.h:110:49: warning: 'EC_KEY_free' is deprecated [-Wdeprecated-declarations]
  110 | FOLLY_SSL_DETAIL_DEFINE_PTR_TYPE(EcKey, EC_KEY, EC_KEY_free);
      |                                                 ^
buck-out/v2/gen/fbcode/0d02068896024821/antlir/distro/deps/openssl/__ssl--outputs__/outs/headers/openssl/ec.h:1022:1: note: 'EC_KEY_free' has been explicitly marked deprecated here
 1022 | OSSL_DEPRECATEDIN_3_0 void EC_KEY_free(EC_KEY *key);
      | ^
buck-out/v2/gen/fbcode/0d02068896024821/antlir/distro/deps/openssl/__ssl--outputs__/outs/headers/openssl/macros.h:217:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
  217 | #   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
      |                                                 ^
buck-out/v2/gen/fbcode/0d02068896024821/antlir/distro/deps/openssl/__ssl--outputs__/outs/headers/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
   62 | #     define OSSL_DEPRECATED(since) __attribute__((deprecated))
      |                                                    ^
In file included from fbcode/tee/tee_routing_service/client_routing/Utils.cpp:3:
In file included from buck-out/v2/gen/fbcode/0d02068896024821/tee/tee_routing_service/client_routing/__utils__/buck-headers/tee/tee_routing_service/client_routing/Utils.h:5:
buck-out/v2/gen/fbcode/0d02068896024821/folly/ssl/__openssl_ptr_types__/buck-headers/folly/ssl/OpenSSLPtrTypes.h:118:44: warning: 'DSA_free' is deprecated [-Wdeprecated-declarations]
  118 | FOLLY_SSL_DETAIL_DEFINE_PTR_TYPE(Dsa, DSA, DSA_free);
      |                                            ^
buck-out/v2/gen/fbcode/0d02068896024821/antlir/distro/deps/openssl/__ssl--outputs__/outs/headers/openssl/dsa.h:132:1: note: 'DSA_free' has been explicitly marked deprecated here
  132 | OSSL_DEPRECATEDIN_3_0 void DSA_free(DSA *r);
      | ^
buck-out/v2/gen/fbcode/0d02068896024821/antlir/distro/deps/openssl/__ssl--outputs__/outs/headers/openssl/macros.h:217:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
  217 | #   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
      |                                                 ^
buck-out/v2/gen/fbcode/0d02068896024821/antlir/distro/deps/openssl/__ssl--outputs__/outs/headers/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
   62 | #     define OSSL_DEPRECATED(since) __attribute__((deprecated))
      |                                                    ^
In file included from fbcode/tee/tee_routing_service/client_routing/Utils.cpp:7:
buck-out/v2/gen/fbcode/0d02068896024821/antlir/distro/deps/re2/__re2--outputs__/outs/headers/re2/re2.h:220:10: fatal error: 'absl/base/call_once.h' file not found
  220 | #include "absl/base/call_once.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~
4 warnings and 1 error generated.
Error: command failed
Buck UI: https://www.internalfb.com/buck2/86414966-2e6b-48b4-8d4e-6aae54109810
Network: Up: 4.2MiB  Down: 11MiB  (reSessionID-1dc554b8-069f-46a9-8ae5-d4fc0dbfb460)
Analyzing targets. Remaining     0/53                                                                                                           1138 actions, 1200 artifacts declared
Executing actions. Remaining     0/1297                                                                                                         1:31.6s exec time total
Command: build.    Finished 202 local, 2 cache (1% hit)                                                                                         18.5s exec time cached (20%)
Time elapsed: 3.9s
BUILD FAILED
Failed to build 'fbcode//tee/tee_routing_service/client_routing:utils (cfg:opt-linux-x86_64-clang19-no-san-opt-by-default#0d02068896024821)'
```
Let's add this as a header-only lib (looks like we don't need to expose the actual libraries).

Test Plan:
CI

cent10 build works now:
```
$ buck build --flagfile fbcode//mode/dev fbcode//tee/snp/image/examples/sidecar/centos10/cvm_fbpkg:tee.snp.tw.cvm.sidecar_example.c10__hash_tree__extract_rootfs
File changed: fbcode//antlir/distro/deps/libtiff/BUCK
File changed: fbcode//antlir/distro/platform/BUCK
File changed: fbcode//antlir/distro/toolchain/python/BUCK
29 additional file change events
Buck UI: https://www.internalfb.com/buck2/1642100b-71cb-4413-9ed8-4b85f1def898
Network: Up: 0B  Down: 512MiB  (reSessionID-914d3c82-af9c-4498-9a63-2d324fe4e80b)
Loading targets.   Remaining      0/44844                                                                                                       3 dirs read, 1307731 targets declared
Analyzing targets. Remaining      0/175884                                                                                                      1109971 actions, 1224736 artifacts declared
Executing actions. Remaining      0/184105
Command: build.
Time elapsed: 25.6s
BUILD SUCCEEDED
```

Rollback Plan:

Reviewed By: vmagro

Differential Revision: D77238820

fbshipit-source-id: d63d4a3178bb2be8abfd909f157cec43819f0e24