Fix autodeps failure in stat.bzl
Summary:
autodeps uses python and dies in stat.bzl:
```
...
      File "antlir/bzl/stat.bzl", line 53, in _parse_symbolic
        classes = list(classes.elems())
    AttributeError: 'str' object has no attribute 'elems'
```

Switch to something that works in buck and python.

Reviewed By: sergeyfd

Differential Revision: D38815111

fbshipit-source-id: d04267c8b1cdf4d2553aa41de5151b224b422509