antlir: Fix deps for vm/tests:python-remote-execution
Summary: - Forgot to specify some dependencies here

Test Plan:
Before:

```
$ cd ~/fbcode/antlir/vm/tests
$ buck run :python-remote-execution  -- --append-console /dev/null
...
    from antlir.fs_utils import Path
ModuleNotFoundError: No module named 'antlir.fs_utils'
...
```

After:

```
$ cd ~/fbcode/antlir/vm/tests
$ buck run :python-remote-execution -- --append-console /dev/null
...
test_os_booted (antlir.vm.tests.test_vm_boot.BootVMTest) ... ok
test_os_hostname (antlir.vm.tests.test_vm_boot.BootVMTest) ... ok

----------------------------------------------------------------------
Ran 2 tests in 0.016s

OK
I 20230614 07:04:10.232 354519 vmtest.py:380 [b'/data/users/pdel/fbsource/buck-out/v2/gen/fbcode/67e0758f7bdffa6c/antlir/
vm/tests/__python-remote-execution__test_binary__/python-remote-execution__test_binary.par'] completed with: 0
D 20230614 07:04:10.233 354519 guest_ssh.py:44 Exit ssh context.  Remove private key: /tmp/tmpdyrw5107
D 20230614 07:04:10.233 354519 vm.py:577 Sending kill to VM: 354781
D 20230614 07:04:10.271 354519 vm.py:587 VM -KILL returned with: 0
D 20230614 07:04:10.271 354519 vm.py:590 Wait for VM to terminate via kill
D 20230614 07:04:10.271 354519 vm.py:601 VM exited with: -9
```

Reviewed By: snarkmaster

Differential Revision: D46724668

fbshipit-source-id: a0cb7c920cf0a6131172a49b1b3904b9df2c3dd3