[buck2] rust: Fix python module name collision
Summary:
Ok so... D53759272 broke a couple people's things with errors that look like this:

```
ImportError: PyO3 modules may only be initialized once per interpreter process
```

The true evil that causes this is that python modules coming from native python extensions are globally namespaced - even if they're submodules. Specifically, a module `libcst.native` has an initialization function with the symbol name `PyInit_native`. That ends up colliding with the initialization function for `antlir.rust.native`, and so we end up with the error.

The way that C++ deals with this is with a bunch of code in the rules that jumps through hoops to mangle things by manually rewriting symbol names and then pulling other tricks to get that to work transparently.

Unfortunately, Rust doesn't have a native `rust_python_extension`, and that approach can't be easily extended to the macros; as a result, the mangling thing is disabled for Rust.

So how do we deal with this? The proper way to do it would be to implement `rust_python_extension` in the rules. I, however, have enough on my plate, and so I'm just gonna deal with this by renaming the antlir module and pretending that now everything is fine

Test Plan:
```
> buck2 test @//mode/opt //tupperware/image/scripts/cm/migrate/tests:test-tw-delete-code -- test_package_arg_out_of_scope
> buck2 run mode/opt //scribe/tools/scribeshell:scribeshell -- --dry-run consumers feature_rollout_update use_coro_for_read_service_connector_v3 stable 1
```

CI

Reviewed By: ivendor

Differential Revision: D53806357

fbshipit-source-id: 708aeb6983e143b08bf228efe92c28a140425ab4