antlir: Revert back to gcc 11 toolset
Summary:
While trying to build the TTS service I ran into the following issue:
```
In file included from xplat/langtech/titanium/utils/StringHelper.cpp:9:
buck-out/v2/gen/fbsource/7d32d8419ca5e4a1/xplat/langtech/titanium/utils/__unicode__/buck-headers/langtech/titanium/utils/unicode.h:126:59: error: unknown type name 'uint32_t'
  126 | [[nodiscard]] char32_t decodeUtf8(std::string const& str, uint32_t& pos);
      |                                                           ^
xplat/langtech/titanium/utils/StringHelper.cpp:270:5: error: unknown type name 'uint32_t'
  270 |     uint32_t ch = 0;
      |     ^
2 errors generated.
Error: command failed
```
`uint32_t` is a pretty standard integral type; what gives? These types come from `cstdint` (or `stdint.h` for C).

Turns out that glibc headers from gcc-14 are quite different from the (very) old gcc-11 we use internally.

The include path for this same compile from gcc-11 (internal), snipped to where we include assert.h:
```
... fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/char_traits.h
.... fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/stl_algobase.h
..... fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/functexcept.h
...... fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/exception_defines.h
..... fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/cpp_type_traits.h
..... fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/ext/type_traits.h
..... fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/ext/numeric_traits.h
..... fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/stl_pair.h
...... fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/move.h
....... fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/type_traits
...... fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/compare
....... fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/concepts
..... fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/stl_iterator_base_types.h
...... fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/iterator_concepts.h
....... fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/ptr_traits.h
....... fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/ranges_cmp.h
..... fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/stl_iterator_base_funcs.h
...... fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/concept_check.h
...... fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/debug/assertions.h
..... fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/stl_iterator.h
...... fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/new
....... fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/exception
........ fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/exception.h
........ fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/exception_ptr.h
......... fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/cxxabi_init_exception.h
.......... fbcode/third-party-buck/platform010/build/llvm-fb/19/lib/clang/stable/include/stddef.h
........... fbcode/third-party-buck/platform010/build/llvm-fb/19/lib/clang/stable/include/__stddef_header_macro.h
........... fbcode/third-party-buck/platform010/build/llvm-fb/19/lib/clang/stable/include/__stddef_ptrdiff_t.h
........... fbcode/third-party-buck/platform010/build/llvm-fb/19/lib/clang/stable/include/__stddef_size_t.h
........... fbcode/third-party-buck/platform010/build/llvm-fb/19/lib/clang/stable/include/__stddef_wchar_t.h
........... fbcode/third-party-buck/platform010/build/llvm-fb/19/lib/clang/stable/include/__stddef_null.h
........... fbcode/third-party-buck/platform010/build/llvm-fb/19/lib/clang/stable/include/__stddef_nullptr_t.h
........... fbcode/third-party-buck/platform010/build/llvm-fb/19/lib/clang/stable/include/__stddef_max_align_t.h
........... fbcode/third-party-buck/platform010/build/llvm-fb/19/lib/clang/stable/include/__stddef_offsetof.h
......... fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/typeinfo
.......... fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/hash_bytes.h
......... fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/new
........ fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/nested_exception.h
..... fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/debug/debug.h
..... fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/predefined_ops.h
.... fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/postypes.h
..... fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/cwchar
...... fbcode/third-party-buck/platform010/build/glibc/include/wchar.h
....... fbcode/third-party-buck/platform010/build/glibc/include/bits/libc-header-start.h
....... fbcode/third-party-buck/platform010/build/glibc/include/bits/floatn.h
........ fbcode/third-party-buck/platform010/build/glibc/include/bits/floatn-common.h
......... fbcode/third-party-buck/platform010/build/glibc/include/bits/long-double.h
....... fbcode/third-party-buck/platform010/build/llvm-fb/19/lib/clang/stable/include/stddef.h
........ fbcode/third-party-buck/platform010/build/llvm-fb/19/lib/clang/stable/include/__stddef_size_t.h
........ fbcode/third-party-buck/platform010/build/llvm-fb/19/lib/clang/stable/include/__stddef_wchar_t.h
........ fbcode/third-party-buck/platform010/build/llvm-fb/19/lib/clang/stable/include/__stddef_null.h
....... fbcode/third-party-buck/platform010/build/llvm-fb/19/lib/clang/stable/include/stdarg.h
........ fbcode/third-party-buck/platform010/build/llvm-fb/19/lib/clang/stable/include/__stdarg___gnuc_va_list.h
....... fbcode/third-party-buck/platform010/build/glibc/include/bits/wchar.h
....... fbcode/third-party-buck/platform010/build/glibc/include/bits/types/wint_t.h
....... fbcode/third-party-buck/platform010/build/glibc/include/bits/types/mbstate_t.h
........ fbcode/third-party-buck/platform010/build/glibc/include/bits/types/__mbstate_t.h
....... fbcode/third-party-buck/platform010/build/glibc/include/bits/types/__FILE.h
....... fbcode/third-party-buck/platform010/build/glibc/include/bits/types/FILE.h
....... fbcode/third-party-buck/platform010/build/glibc/include/bits/types/locale_t.h
........ fbcode/third-party-buck/platform010/build/glibc/include/bits/types/__locale_t.h
.... fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/cwchar
.... fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/cstdint
```
i.e. it goes `bits/char_traits.h` --> `cstdint`.

The same, but using gcc-14:
```
... buck-out/v2/gen/fbcode/347daf4cb899e0f3/antlir/distro/deps/libgcc/__stdc++-headers__/14/bits/char_traits.h
.... buck-out/v2/gen/fbcode/347daf4cb899e0f3/antlir/distro/deps/libgcc/__stdc++-headers__/14/bits/postypes.h
..... buck-out/v2/gen/fbcode/347daf4cb899e0f3/antlir/distro/deps/libgcc/__stdc++-headers__/14/cwchar
...... buck-out/v2/gen/fbcode/347daf4cb899e0f3/antlir/distro/toolchain/cxx/__sysroot-layer__/remove/subvol_symlink/usr/include/wchar.h
....... buck-out/v2/gen/fbcode/347daf4cb899e0f3/antlir/distro/toolchain/cxx/__sysroot-layer__/remove/subvol_symlink/usr/include/bits/libc-header-start.h
....... buck-out/v2/gen/fbcode/347daf4cb899e0f3/antlir/distro/toolchain/cxx/__sysroot-layer__/remove/subvol_symlink/usr/include/bits/floatn.h
........ buck-out/v2/gen/fbcode/347daf4cb899e0f3/antlir/distro/toolchain/cxx/__sysroot-layer__/remove/subvol_symlink/usr/include/bits/floatn-common.h
......... buck-out/v2/gen/fbcode/347daf4cb899e0f3/antlir/distro/toolchain/cxx/__sysroot-layer__/remove/subvol_symlink/usr/include/bits/long-double.h
....... /usr/bin/../lib/clang/19/include/stddef.h
........ /usr/bin/../lib/clang/19/include/__stddef_size_t.h
........ /usr/bin/../lib/clang/19/include/__stddef_wchar_t.h
........ /usr/bin/../lib/clang/19/include/__stddef_null.h
....... /usr/bin/../lib/clang/19/include/stdarg.h
........ /usr/bin/../lib/clang/19/include/__stdarg___gnuc_va_list.h
....... buck-out/v2/gen/fbcode/347daf4cb899e0f3/antlir/distro/toolchain/cxx/__sysroot-layer__/remove/subvol_symlink/usr/include/bits/wchar.h
....... buck-out/v2/gen/fbcode/347daf4cb899e0f3/antlir/distro/toolchain/cxx/__sysroot-layer__/remove/subvol_symlink/usr/include/bits/types/wint_t.h
....... buck-out/v2/gen/fbcode/347daf4cb899e0f3/antlir/distro/toolchain/cxx/__sysroot-layer__/remove/subvol_symlink/usr/include/bits/types/mbstate_t.h
........ buck-out/v2/gen/fbcode/347daf4cb899e0f3/antlir/distro/toolchain/cxx/__sysroot-layer__/remove/subvol_symlink/usr/include/bits/types/__mbstate_t.h
....... buck-out/v2/gen/fbcode/347daf4cb899e0f3/antlir/distro/toolchain/cxx/__sysroot-layer__/remove/subvol_symlink/usr/include/bits/types/__FILE.h
....... buck-out/v2/gen/fbcode/347daf4cb899e0f3/antlir/distro/toolchain/cxx/__sysroot-layer__/remove/subvol_symlink/usr/include/bits/types/FILE.h
....... buck-out/v2/gen/fbcode/347daf4cb899e0f3/antlir/distro/toolchain/cxx/__sysroot-layer__/remove/subvol_symlink/usr/include/bits/types/locale_t.h
........ buck-out/v2/gen/fbcode/347daf4cb899e0f3/antlir/distro/toolchain/cxx/__sysroot-layer__/remove/subvol_symlink/usr/include/bits/types/__locale_t.h
.... buck-out/v2/gen/fbcode/347daf4cb899e0f3/antlir/distro/deps/libgcc/__stdc++-headers__/14/cwchar
.... buck-out/v2/gen/fbcode/347daf4cb899e0f3/antlir/distro/deps/libgcc/__stdc++-headers__/14/type_traits
```
No cstdint!

The [gcc-14 char_traits.h file is here](https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/include/bits/char_traits.h#L51-L60). The bit of code in question is:
```
#if __cplusplus >= 201103L
# include <type_traits>
#if !defined __UINT_LEAST16_TYPE__ || !defined __UINT_LEAST32_TYPE__
# include <cstdint>
#endif
#endif
#if __cplusplus >= 202002L
# include <compare>
# include <bits/stl_construct.h>
#endif
```
I suspect that somehow `__UINT_LEAST16_TYPE__` (or `__UINT_LEAST32_TYPE__`) is defined by something, which means we never include cstdint in here. It's a bit weird that nothing else includes cstdint at all.

Moving to gcc-11 fixes things.

Test Plan:
Build it with gcc-11, it gets past that and onto something else (fixed in next diff):
```
$ buck bxl fbcode//tee/bxl/compatibility.bxl:build -- --target fbsource//xplat/langtech/tuna/cli:tuclix
File changed: fbsource//xplat/langtech/titanium/utils/StringHelper.cpp
File changed: fbcode//antlir/distro/deps/libgcc/BUCK
File changed: fbcode//antlir/distro/deps/libgcc/defs.bzl
Action failed: fbsource//xplat/langtech:MultiChannelFrontends (cxx_compile frontend/MultiChannelFrontends.cpp)
Remote command returned non-zero exit code 1
Reproduce locally: `frecli cas download-action 5020b584f2b6b5554bd1c775ca11c2bcd1a5a12f59f3da0b052f3421b67e3c2a:145`
stdout:
stderr:
2025-07-17T04:43:28.430365Z TRACE unshare_new_userns: antlir2_rootless: looking up best subid ranges for 30083 (fbnobody)
2025-07-17T04:43:28.430431Z TRACE unshare_new_userns: antlir2_rootless: using uid range Range { start: Uid(493216), len: IdOffset(65536) } and gid range Range { start: Gid(493216), len: IdOffset(65536) }
In file included from xplat/langtech/frontend/MultiChannelFrontends.cpp:8:
In file included from ./xplat/folly/logging/xlog.h:26:
./xplat/folly/logging/LoggerDB.h:60:14: error: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
   60 |   LogCategory* getCategory(folly::StringPiece name);
      |              ^
./xplat/folly/logging/LoggerDB.h:60:14: note: insert '_Nullable' if the pointer may be null
   60 |   LogCategory* getCategory(folly::StringPiece name);
      |              ^
      |                _Nullable
```

Rollback Plan:

Reviewed By: vmagro

Differential Revision: D78465860

fbshipit-source-id: e54ee61ec4315ba0b2a174bbf166addf5667db52