[antlir2][vm] improve command logging format
Summary:
Make it obvious when the args are messed up. This was never a problem
before when all commands are constructed internally. However, with sidecar and
test args passed in from buck, the concatenated string that looks the same may
not be the same. This was the reason that some of the sidecar args aren't
working as expected.

Test Plan:
Verify it can catch the problem when I mess up args.
```name=detect the last malformatted command
$ RUST_LOG=debug buck run antlir/antlir2/antlir2_vm/tests:test-sidecar[shell]
2023-08-17T23:32:10.255209Z DEBUG antlir2_vm::utils: Executing command: Program: `ip`. Args: `["tuntap", "add", "dev", "vm0", "mode", "tap"]`
2023-08-17T23:32:10.262566Z DEBUG antlir2_vm::utils: Executing command: Program: `ip`. Args: `["link", "set", "vm0", "up"]`
2023-08-17T23:32:10.264831Z DEBUG antlir2_vm::utils: Executing command: Program: `ip`. Args: `["addr", "add", "fd00::1/64", "dev", "vm0"]`
2023-08-17T23:32:10.267338Z DEBUG antlir2_vm::utils: Executing command: Program: `buck-out/v2/gen/fbcode/2621749e493eace7/antlir/antlir2/antlir2_vm/tests/__sidecar__/shared/sidecar`. Args: `[]`
2023-08-17T23:32:10.267439Z DEBUG antlir2_vm::vm: Waiting for notify file to be created
2023-08-17T23:32:10.267598Z DEBUG antlir2_vm::utils: Executing command: Program: `buck-out/v2/gen/fbcode/2621749e493eace7/antlir/antlir2/antlir2_vm/tests/__sidecar__/shared/sidecar --port 8001`. Args: `[]`
2023-08-17T23:32:10.367595Z ERROR antlir2_vm::vm: msg="Sidecar service at index 1 finished unexpectedly"
2023-08-17T23:32:10.367636Z ERROR antlir2_vm::vm: Exit status Err(
    SidecarError(
        Os {
            code: 2,
            kind: NotFound,
            message: "No such file or directory",
        },
    ),
)
Error: Failed to start sidecar process: `Sidecar service at index 1 finished unexpectedly'
```

Differential Revision: D48455544

fbshipit-source-id: 540efab0bedde1551dc9f6216ebc46872165f8c1