[antlir2][rpms] better format of package-not-found error
Summary: Instead of dumping a dnf stacktrace, record a first-class error

Test Plan:
```
vmagro@devvm11640.ftw0 in fbsource
❯ hg diff
 diff --git a/fbcode/antlir/antlir2/test_images/rpms/TARGETS b/fbcode/antlir/antlir2/test_images/rpms/TARGETS
 --- a/fbcode/antlir/antlir2/test_images/rpms/TARGETS
+++ b/fbcode/antlir/antlir2/test_images/rpms/TARGETS
@@ -43,6 +43,7 @@
                 "foo-2",
                 # this depends on 'foobar' and 'foobarbaz' should be removed when 'foobar' is
                 "foobarbaz",
+                "qux",  # this does not exist
             ],
         ),
         ":test-deps",

vmagro@devvm11640.ftw0 in fbsource
❯ buck build fbcode//antlir/antlir2/test_images/rpms:simple--layer
...
Error: there were one or more transaction errors: ["No such package found 'qux'"]

Uncategorized(
    "isolated command failed: exit status: 1",
)
"isolated command failed: exit status: 1"
```

Reviewed By: epilatow

Differential Revision: D47776412

fbshipit-source-id: b465eb49704769aa99ed274cd5a6953945f07a1c