Eliminate `set_up_volume.sh` "ERROR" logspam
Summary:
Typical Antlir output includes these log lines, which are not true errors:

```
ERROR: mount check: cannot open /.../buck-image-out/image.btrfs: No such file or directory
ERROR: could not check mount status: No such file or directory
```

This causes customer confusion and other issues.

The new implementation is quieter, and also more "technically correct".

Reviewed By: zeroxoneb

Differential Revision: D35683390

fbshipit-source-id: b353a11cc6d5e5dd442eff3e122c8c287cd957b8