[antlir2][vm] make the error message more clear
Summary:
Turns out boot can fail in a way that doesn't quit qemu and make it
look like it's stuck.

For example: https://fburl.com/testinfra/jy9saer8
> [!!!!!!] Failed to isolate default target.
[   13.660160] systemd[1]: Freezing execution.

Thus this `Resource temporarily unavailable (os error 11)` error can be a
legitimate boot failure, instead of some potential host issue that I usually
only see during stress test. Guess now we have to check console log for each
such failure in order to know if it's a boot issue, or some other mysterious
failure.

Test Plan:
Run a currently failing test to get failure output.
https://www.internalfb.com/intern/testinfra/diagnostics/16888498639074488.281475090865177.1717461583/

> Error: Failed to boot VM: Failed to read boot event from the notify socket. This
        indicates the VM failed to boot to default target. Please check the
        console log for further analysis.: `Resource temporarily unavailable (os error 11)`

Reviewed By: cooperlees

Differential Revision: D58117322

fbshipit-source-id: 7510eb95b1ed1e431eb86b1cc3eb3f181b86be36