[antlir2][bzl][image_test] Allow running image tests from any path
Summary:
Only `buck test` would work from anywhere due to `run_from_project_root = True`, but any attempt to `buck run` would require running from the root of the repo to work.

To address, we:
1. Set `absolute = True`
2. Change the working directory to the project root prior to executing the script

This is OK for caching since these scripts are not used as inputs for anything else.

This eliminates the possibility of hitting the following due to running from the wrong working directory (where the root-relative path to the subvol_symlink is invalid):

```
systemctl get-default failed: Failed to get default target: No such file or directory

Error: systemctl get-default failed: Failed to get default target: No such file or directory
```

Test Plan:
Run from `fbsource`, `fbsource/fbcode` and `fbsource/fbcode/rl_robot`:
```
buck2 test fbcode//mode/opt fbcode//rl_robot/system/dev/services/image_decoder:integration_test
buck2 run fbcode//mode/opt fbcode//rl_robot/system/dev/services/image_decoder:integration_test
buck2 run fbcode//mode/opt fbcode//rl_robot/system/dev/services/image_decoder:integration_test[container]
```

Rollback Plan:

Reviewed By: vmagro

Differential Revision: D80973226

fbshipit-source-id: e6fab9f00884a5f437aa25f08079906032a9cee7