Fix breakages with the c7 snapshot update in D36322684
Summary:
With the snapshot update in D36322684 we now have an exception when trying to `buck build //tupperware/image/slimos:slimos-subfloor` that shows the error
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/yum/rpmtrans.py", line 464, in callback
    self._unInstStop( bytes, total, h )
  File "/usr/lib/python2.7/site-packages/yum/rpmtrans.py", line 571, in _unInstStop
    pid   = self.base.history.pkg2pid(txmbr.po)
  File "/usr/lib/python2.7/site-packages/yum/history.py", line 809, in pkg2pid
    return self._ipkg2pid(po, create)
  File "/usr/lib/python2.7/site-packages/yum/history.py", line 803, in _ipkg2pid
    return self._pkgtup2pid(po.pkgtup, csum, create)
  File "/usr/lib/python2.7/site-packages/yum/history.py", line 764, in _pkgtup2pid
    epoch=? AND version=? AND release=?""", pkgtup)
  File "/usr/lib/python2.7/site-packages/yum/sqlutils.py", line 168, in executeSQLQmark
    return cursor.execute(query, params)
AttributeError: 'NoneType' object has no attribute 'execute'
FATAL ERROR: python callback <bound method RPMTransaction.callback of <yum.rpmtrans.RPMTransaction instance at 0x7fdd1e35f098>> failed, aborting!
E 20220511 16:07:45.967 yum_dnf_from_snapshot.py:834 YumDnfError(returncode=1) while running `yum --installroot=/workZr1oQj6ISFWOE8IP8JFybQ remove-n --assumeyes rpcbind tcpdump` from snapshot `/__antlir__/rpm/default-snapshot-for-installer/yum`. For more logs, run your container and `yum` command with `ANTLIR_DEBUG=1`.
```
In theory `yum remove-n` should be a no-op if the rpm is not installed, so this looks like a bug with yum itself. Removing the `rpms_remove_if_exists` since it doesn't exist on the image anyways.

We also add the missing users to android-cg-tests

Reviewed By: zeroxoneb

Differential Revision: D36331467

fbshipit-source-id: 2d5adc210ccc5c9dd0a30a3b1e2165e7732fdf3f