[antlir2] Make MountHandle which enforces umount ordering is correct
Summary: This extends the `Mounter` trait to return a new type `MountHandle` which won't allow you to umount things if you have mounted things inside of it using the same chain of handles.

Test Plan:
Made a test that shouldn't compile:
{P671900260}

and saw that it won't:
```
error[E0505]: cannot move out of `parent` because it is borrowed
   --> antlir/antlir2/antlir2_package/antlir2_btrfs_packager/src/main.rs:205:5
    |
195 |       let child = parent
    |  _________________-
196 | |         .mount_relative(
197 | |             Path::new("/dev/sda2"),
198 | |             Path::new("home"),
...   |
201 | |             None,
202 | |         )
    | |_________- borrow of `parent` occurs here
...
205 |       parent.umount(false);
    |       ^^^^^^ move out of `parent` occurs here
206 |       child.umount(false);
    |       ----- borrow later used here

```

Reviewed By: zeroxoneb

Differential Revision: D44520962

fbshipit-source-id: 89fc1f18106e098198d18974bb72e600842ae40f