[antlir2] buck1 fixes for antlir2_migration.bzl
Summary: This didn't eval on buck1

Test Plan:
Before
```
❯ /usr/local/bin/buck1 targets fbcode//arvr/fbpkg_builders/augment:vros.augment
Action graph will be rebuilt because files have been added or removed.
ERROR: /data/users/vmagro/fbsource/fbcode/antlir/bzl/build_defs_impl.bzl:666:62: name 'host_info' is not defined
Parsing buck files... 0.7 sec
Cannot parse /data/users/vmagro/fbsource/fbcode/antlir/bzl/build_defs_impl.bzl

This error happened while trying to get dependency 'fbcode//bot_generated/antlir/fbpkg/db:fbpkg.builder-entrypoint/repo_stable-USE-fbpkg.fetched_with_nondeterministic_fs_metadata' of target 'fbcode//antlir/fbpkg/build:fbpkg-builder-cached'
    At /data/users/vmagro/fbsource/fbcode/antlir/bzl/build_defs.bzl:10:6
    At /data/users/vmagro/fbsource/fbcode/antlir/bzl/structs.bzl:6:6
    At /data/users/vmagro/fbsource/fbcode/antlir/bzl/types.bzl:16:6
    At /data/users/vmagro/fbsource/fbcode/antlir/bzl/antlir2_migration.bzl:7:6
    At /data/users/vmagro/fbsource/fbcode/bot_generated/antlir/fbpkg/db/PACKAGE:1:6
```

After
```
❯ /usr/local/bin/buck1 targets //arvr/fbpkg_builders/augment:vros.augment
DEBUG: /data/users/vmagro/fbsource/tools/build_defs/fbcode_macros/build_defs/lib/python_common.bzl:2471:18: WARNING: You're using buck1 to build an inplace Python binary that has main_function set. This doesn't generally work, please migrate to buck2.
DEBUG: /data/users/vmagro/fbsource/tools/build_defs/fbcode_macros/build_defs/lib/python_common.bzl:2471:18: WARNING: You're using buck1 to build an inplace Python binary that has main_function set. This doesn't generally work, please migrate to buck2.
Parsing buck files: finished in 31.7 sec
//arvr/fbpkg_builders/augment:vros.augment
```

Reviewed By: justintrudell

Differential Revision: D50563930

fbshipit-source-id: 214aca286963a80c74787f6b97ea915c7ef30577