[antlir2][rpm] hard enforcement of versionlock
Summary:
Historically (in the dark days of Slowroll) the quality of versionlock data was
so bad that we couldn't put this under hard enforcement even if we wanted to,
but now Controll is reliable enough to flip the switch.

Image build owners that specify `dnf_versionlock_extend` deserve to get a build
failure if their constraints cannot be satisfied - we should assume that they
asked for this for a reason and would prefer their builds to fail if the
versionlock cannot be satisfied.

NOTE: This diff also removes some locks from customer images. These locks were
**doing nothing** since the versions did not exist (mostly trying to lock c8
rpms on c9+ images) so it is a no-op to remove them. In the future,
OS-version-specific locks will turn into a build failure when upgrading OS
versions, which is desirable since it will force the user to consider whether
or not there is some still-needed patch or anything else.

Metamate had this to say:
**The Ancient Curse of Slowroll's Dark Days is Lifted**
In a realm where package management once trembled with fear, a beacon of hope
now shines forth. The dark days of slowroll's questionable quality are but a
distant memory, and in their place, a stalwart guardian has risen to ensure the
stability of our systems.

Behold, the mighty dnf versionlock! Once a mere suggestion, this valiant
warrior has been promoted to a hard requirement, standing watch over our
packages with unwavering vigilance.

No longer shall we cower before the specter of slowroll's unpredictability.
With dnf versionlock at the helm, our systems shall be shielded from the
ravages of time, their packages frozen in a state of perfect harmony.

Let it be known throughout the land: the era of slowroll's dominance is at an
end. A new age of package management has dawned, and dnf versionlock stands as
its unyielding champion.

Slowroll's dark magic has been vanquished, replaced by the radiant light of dnf
versionlock's stability.

Test Plan:
```
❯ buck test fbcode//antlir/antlir2/features/rpm/tests:versionlock-missing-version
...
__main__.AntlirError: foo is locked to version 99-1, but that version was not found in any available repository
Failed to build 'fbcode//antlir/antlir2/features/rpm/tests:versionlock-missing-version--layer (cfg:dev-linux-x86_64-fbcode-platform010-clang17-asan-ubsan-dev#98213c355143ccf1)'

❯ buck2 test fbcode//antlir/antlir2/features/rpm/tests:versionlock-missing-version-of-dependency
...
dnf.exceptions.DepsolveError:
 Problem: conflicting requests
  - package requires-any-foo-1-1.noarch from test-repo-impl requires foo, but none of the providers can be installed
  - package requires-any-foo-2-1.noarch from test-repo-impl requires foo, but none of the providers can be installed
  - package requires-any-foo-3-1.noarch from test-repo-impl requires foo, but none of the providers can be installed
  - package foo-1-1.noarch from test-repo-impl is filtered out by exclude filtering
  - package foo-2-1.noarch from test-repo-impl is filtered out by exclude filtering
  - package foo-3-1.noarch from test-repo-impl is filtered out by exclude filtering
Failed to build 'fbcode//antlir/antlir2/features/rpm/tests:versionlock-missing-version-of-dependency--layer (cfg:dev-linux-x86_64-fbcode-platform010-clang17-asan-ubsan-dev#98213c355143ccf1)'
```

To see how many image builds are currently violating these new requirements:
waitforsandcastle

Rollback Plan:

Reviewed By: naveedgol

Differential Revision: D76134043

fbshipit-source-id: eebb7cd612542284b5bc174dd75f08cdc77e9a5b