[antlir][vm] Make the virtio-notify resilient to transient sshd service start failures
Summary:
We have some vmtests that are flakey, where we get the output:

```
2024-04-06T01:48:33.599909Z  INFO antlir2_vm::vm: Note: console output is redirected to /data/users/elnikety/fbsource/buck-out/v2/test/20240405-183837/dfb483a9-7ae2-4463-ba76-bea9c4bbf769/artifacts_directory/console.txt
Warning: Cannot announce submounts, client does not support it
Warning: Cannot announce submounts, client does not support it
Warning: Cannot announce submounts, client does not support it
Error: Failed to boot VM: Failed to read notify socket: `Resource temporarily unavailable (os error 11)`
```

To debug this further, I used this little hack from Junjie ( P1199116558 ) to direct systemd output to console. Here is a capture of what is going on:

* `sshd` fails to start because of "no hostkeys available". See here ( https://fburl.com/testinfra/ycga8utm ) at L4851. A couple of lines ealier, sshd complains about not finding `ssh_host_ed25519_key` which seem to be distinct to that type of failure.
* In the same run, if you go to lines 5935-5952, you can see that sshd was restarted *successfully* at a later point. This indicates that whatever failure earlier was transient. (Maybe some IO errors due to load?)
* The virtio-notify uses `After=`. This means, even if sshd becomes active at a later point, there is no reason for systemd to re-attempt running the unit since the failure was "dependency failure".

This diff addresses this corner case by moving the conditional sshd.service from a dependency to a service condition. This will make systemd reattempt running the virtio-notify upon failure, opposed to completely bailing out due to dependency failure.

Was able to reproduce the problematic behaviour after the fix. See [here](https://fburl.com/testinfra/cr9s85yc). With the change, you can see:
1\ sshd service fails to start: L4845
2\ virtio-notify fails as well: L4921
3\ sshd service evetually starts: L5933
4\ virtio-notify succeeds: L5946
.. which allows the vmtest to continue as normal. Success!

Test Plan:
Ran the stress test many times in a row and haven't observed failures.

```
RUST_LOG=debug buck2 test 'fbcode//mode/opt' fbcode//tupperware/vmtest/hostagent/integration:host-agent-image-reboot -- --run-disabled  --jobs 50 --stress-runs 50 --record-results
```

https://www.internalfb.com/intern/testinfra/testrun/281475339225469

https://www.internalfb.com/intern/testinfra/testrun/14073748864080409

https://www.internalfb.com/intern/testinfra/testrun/15762598724355138

https://www.internalfb.com/intern/testinfra/testrun/9007199283855765

https://www.internalfb.com/intern/testinfra/testrun/3940649900533973

https://www.internalfb.com/intern/testinfra/testrun/13792273887444937

Reviewed By: wujj123456

Differential Revision: D55843433

fbshipit-source-id: 51da01f8a7f36ef0be9f33cf63633932b20a1d00