[mclassica] Add cyborg to earlyssh
Summary:
After passing attestation root canal uses scp to deliver the host certificate to a machine. We have observed that some portion of the time, this delivery is done with the cyborg user (eg. https://www.internalfb.com/intern/provisioning/asset_details/3337866099792329).

The mclassica centos9 build only allows the user `attestd` in this phase, causing a failure to complete root canal.

```
Unhandled Exception in Step RootcanalPhase.attestation
====== Exception type ======
RemCmdException
====== Exception message ======
(<Cause.ConnectionError: 2>, 'Unable to setup the connection for twshared26667.04.pnb3.facebook.com : Connection lost', 'ConnectionLost')
====== Exception stack ======
Traceback (most recent call last):
  File "/provisioning/statemachine/worker/meta.py", line 485, in static_lambda
    trn = await object_function()
  File "/provisioning/statemachine/phases/rootcanal/phase.py", line 104, in attestation
    actual_host_key_raw: str = await security.get_host_key(
  File "/provisioning/statemachine/phases/rootcanal/security.py", line 45, in get_host_key
    result = await remcmd_lib.run_cmd(
  File "/libfb/py/asyncio/decorators.py", line 331, in new_func
    return await func(*args, **kwargs)
  File "/provisioning/statemachine/lib/remcmd/__init__.py", line 304, in run_cmd
    job_result = await remcmd_thrift.simple_run(
  File "/remcmd/simple/remremcmd.py", line 507, in simple_run
    return await _run(
  File "/remcmd/simple/remremcmd.py", line 370, in _run
    raise results.results[0].ex
remcmd.thrift.exceptions.types.RemCmdException: (<Cause.ConnectionError: 2>, 'Unable to setup the connection for twshared26667.04.pnb3.facebook.com : Connection lost', 'ConnectionLost')
```

The enforcing PAM configuration
```
auth       include system-auth
account [success=1 default=ignore] pam_succeed_if.so quiet user ingroup earlyssh
account    required     pam_nologin.so
account    include system-auth
password   include system-auth
session    include system-auth
```

Rejecting access to the host
```
Dec 12 19:40:27 twshared0977 sshd[4907]: fatal: Access denied for user cyborg by PAM account configuration [preauth] session=twshared0977.03.pnb1.facebook.com:6397f42b.113e
```

Test Plan:
Build rootfs
```
$ buck build //metalos/os/facebook/classic:metalos.classic.c9.sendstream.zst --show-output
```

Mount subvol
```
$ mv buck-out/v2/gen/fbcode/51a2e3424b6c81fa/metalos/os/facebook/classic/__metalos.classic.c9.sendstream.zst__/out/layer.sendstream.zst ./

$ zstd -d layer.sendstream.zst

$ sudo btrfs receive -f layer.sendstream mnt

```

Check Group
```
$ cat mnt/volume/etc/group | grep early
earlyssh:x:36339:cyborg,attestd
```

Differential Revision: D42002483

fbshipit-source-id: d4492a91707b762dc7514650d0e648661907e3de