[antlir] allow type of parent_layer_contents to be Any
Summary:
There seems to be a bug where the types of arguments within `kwargs` get lost within the buck macro layer. This manifested as the error:

```
BUILD FAILED
Error running analysis for `fbsource//third-party/tp2/glibc/2.34:platform010 (cfg:dev-linux-x86_64-fbcode-platform010-clang19-asan-ubsan-dev#731ad6a43b11f314)`
Caused by:
    0: Error running analysis for `fbsource//third-party/tp2/glibc/2.34:platform010-builder (cfg:dev-linux-x86_64-fbcode-platform010-clang19-asan-ubsan-dev#731ad6a43b11f314) (fbcode//buck2/platform/execution:linux-x86_64#487bff3d97ff573b)`
    1: Error running analysis for `fbsource//third-party/tp2/glibc/2.34:platform010-container (cfg:dev-linux-x86_64-fbcode-platform010-clang19-asan-ubsan-dev#731ad6a43b11f314) (fbcode//buck2/platform/execution:linux-x86_64#487bff3d97ff573b)`
    2: Error running analysis for `fbsource//third-party/tp2/glibc/2.34:platform010-image-x86_64.d (cfg:dev-linux-x86_64-fbcode-platform010-clang19-asan-ubsan-dev#731ad6a43b11f314)`
    3: Error running analysis for `fbsource//third-party/tp2/glibc/2.34:platform010-image.d (ovr_config//platform/linux:x86_64-fbcode-platform010-clang#288a3b843396e620)`
    4: Error running analysis for `fbsource//third-party/tp2/glibc/2.34:platform010-image.d (ovr_config//platform/linux:x86_64-fbcode-platform010-clang#06dd3280bfedcfeb)`
    5: Error running analysis for `fbsource//third-party/tp2/glibc/2.34:platform010-image-layer (ovr_config//platform/linux:x86_64-fbcode-platform010-clang#06dd3280bfedcfeb)`
    6: Traceback (most recent call last):
         File <builtin>, in <module>
         * fbcode/buck2/starlark-rust/starlark/src/stdlib/partial.rs:198, in partial
             <native>
         * fbcode/antlir/antlir2/bzl/image/layer.bzl:376, in _impl_with_features
             plan_infos = planner.fn(
         * fbcode/antlir/antlir2/features/rpm/plan.bzl:38, in _plan_fn
             res = plan(
       error: Value `record[LayerContents](subvol_symlink=<build artifact genrule/subvol_symlink bound to fbcode//externals_builder/bzl/toolchain:centos-image-layer (ovr_config//platform/linux:x86_64-fbcode-platform010-clang#06dd3280bfedcfeb)>, subvol_symlink_rootless=True)` of type `record` does not match the type annotation `None | LayerContents` for argument `parent_layer_contents`
         --> fbcode/antlir/antlir2/features/rpm/plan.bzl:38:11
          |
       38 |       res = plan(
          |  ___________^
       39 | |         ctx = ctx,
       40 | |         identifier = identifier,
       41 | |         items = items,
       42 | |         dnf_available_repos = dnf_available_repos,
       43 | |         resolve_cmd = resolve_cmd,
       44 | |         **kwargs
       45 | |     )
          | |_____^
```

See https://www.internalfb.com/diff/D91746778?dst_version_fbid=3964555940342119&transaction_fbid=1543894653580765

This makes the type annotation for the `parent_layer_contents` parameter to `plan` more permissive.

Test Plan:
Tested by running the same repro command rebased on D91753271

```
buck2 run fbsource//third-party/tp2/glibc/2.34:platform010[debug]
```

Reviewed By: igorsugak

Differential Revision: D99465912

fbshipit-source-id: f3f657dedf27f80892d0bddaf58c8200782aa07d