Fix fbpkg.builder build
Summary: Fix regression caused by D50804300

Test Plan:
# Before

```
$ buck2 build fbcode//fblite/unity/snaptuServer:mobile.snaptu.unity
Buck UI: https://www.internalfb.com/buck2/c58f63f2-4f37-41e8-8ec4-037e78f131bd
Network: Up: 0B  Down: 0B
Jobs completed: 3. Time elapsed: 0.6s.
BUILD FAILED
Error running analysis for `fbcode//fblite/unity/snaptuServer:mobile.snaptu.unity (ovr_config//platform/linux:x86_64-fbcode-platform010-clang15-CUDA-projects-cuda-12-cuda-12#9874f87d0ccb406e)`

Caused by:
    0: Error running analysis for `fbcode//fblite/unity/snaptuServer:mobile.snaptu.unity__features_for_cm.antlir2 (ovr_config//platform/linux:x86_64-fbcode-platform010-clang15-CUDA-projects-cuda-12-cuda-12#9874f87d0ccb406e)`
    1: Error running analysis for `fbcode//antlir/antlir2/features:install (fbcode//buck2/platform/execution:linux-x86_64#401f73bfb35974f2)`
    2: Traceback (most recent call last):
         File <builtin>, in <module>
       error: Object of type `provider` has no attribute `non_rust_exported_link_deps`
         --> fbcode/antlir/antlir2/features/defs.bzl:30:16
          |
       30 |     for dep in link_info.non_rust_exported_link_deps:
          |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          |
```

# After

```
$ buck2 build fbcode//fblite/unity/snaptuServer:mobile.snaptu.unity
File changed: fbcode//antlir/antlir2/features/defs.bzl
Buck UI: https://www.internalfb.com/buck2/ffab1ee8-e389-4525-a00b-630484563c59
Network: Up: 0B  Down: 0B
Jobs completed: 86. Time elapsed: 1.7s.
BUILD SUCCEEDED
```

Differential Revision: D50830821

fbshipit-source-id: 7991eb69f9756b47c2ca6da2ddc087429ace140b