[antlir2] fix working_format for implicit layers
Summary:
antlir2 "implicit layers" are weird and swim upstream of how buck configuration
typically works (they are configured top-down while buck configuration is
always bottom-up)

To allow implicit layers to inherit the working format just like they inherit
flavor configuration, a new `"_working_format"` attr magic string was added -
`"inherited"` which will make the rule implementation look at the
`parent_layer` and copy its configuration

Test Plan:
```name="Now"
❯ buck2 test fbcode//mode/opt fbcode//antlir/antlir2/test_images/exec_mode/...
Buck UI: https://www.internalfb.com/buck2/7b5666a3-dc0d-4f0f-8306-d8b2093c1a37
Tests finished: Pass 6. Fail 0. Timeout 0. Fatal 0. Skip 0. Omit 0. Infra Failure 0. Build failure 0
```
https://www.internalfb.com/intern/testinfra/testrun/10133099330693611

```name="Before",counterexample
❯ buck2 test fbcode//mode/opt fbcode//antlir/antlir2/test_images/exec_mode/...
Buck UI: https://www.internalfb.com/buck2/b92efeb6-3b84-452f-bc4a-9797cc54f828
Test UI: https://www.internalfb.com/intern/testinfra/testrun/18858823457419628
Network: Up: 0B  Down: 0B  (reSessionID-5026061b-b6d3-4bfb-8433-a71130338974)
Loading targets.     Remaining      0/82                                                                                                                                       839 targets declared
Analyzing targets.   Remaining      0/144927                                                                                                                                   128 actions, 166 artifacts declared
Executing actions.   Remaining      0/132027                                                                                                                                   5.0s exec time total
Command: test.     Finished 1 local
Time elapsed: 15.5s
Error running analysis for `fbcode//antlir/antlir2/test_images/exec_mode/remote_execution:test-remote-execution (cfg:opt-linux-x86_64-fbcode-platform010-clang19-no-san#e3777cce99df8d33)`

Caused by:
    0: Error running analysis for `fbcode//antlir/antlir2/test_images/exec_mode/remote_execution:test-remote-execution (cfg:opt-linux-x86_64-fbcode-platform010-clang19-no-san#6ec4f69182d76bd4)`
    1: Error running analysis for `fbcode//antlir/antlir2/test_images/exec_mode/remote_execution:test-remote-execution--with-xarexec (cfg:opt-linux-x86_64-fbcode-platform010-clang19-no-san#6ec4f69182d76bd4)`
    2: Error running analysis for `fbcode//antlir/antlir2/test_images/exec_mode/remote_execution:test-remote-execution--with-xarexec (cfg:opt-linux-x86_64-fbcode-platform010-clang19-no-san#ac38017b6bb98485)`
    3: Traceback (most recent call last):
         File <builtin>, in <module>
         * fbcode/buck2/starlark-rust/starlark/src/stdlib/partial.rs:201, in partial
             <native>
         * fbcode/antlir/antlir2/bzl/image/layer.bzl:477, in _impl_with_features
             layer, facts_db = _compile(
         * fbcode/antlir/antlir2/bzl/image/layer.bzl:61, in _compile
             parent_arg = cmd_args(parent.subvol_symlink, format = "--parent={}") if paren...
       error: Type of parameter `args` doesn't match, expected `tuple[Artifact | CellPath | CellRoot | Label | OutputArtifact | ProjectRoot | ResolvedStringWithMacros | TaggedCommandLine | TargetLabel | TransitiveSetArgsProjection | WriteJsonCliArgs | cmd_args | str | list | RunInfo, ...]`, actual `tuple (repr: (None,))`
         --> fbcode/antlir/antlir2/bzl/image/layer.bzl:61:22
          |
       61 |         parent_arg = cmd_args(parent.subvol_symlink, format = "--parent={}") if parent else cmd_args()
          |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          |

1 BUILDS FAILED
Buck UI: https://www.internalfb.com/buck2/b92efeb6-3b84-452f-bc4a-9797cc54f828
Tests finished: Pass 3. Fail 0. Timeout 0. Fatal 0. Skip 0. Omit 0. Infra Failure 0. Build failure 1
```

Reviewed By: naveedgol

Differential Revision: D103221600

fbshipit-source-id: ca1381b4defb41f24667e7f9780f9f30240b8265