[antlir2][vm] check sidecar more often
Summary:
Turns out rust easily runs fast enough that our current check happens
before sidecar getting started or crashed. Save the handles so we can
check in a few key points to ensure they are still running. Ideally we want to
continuously check this, but in that case, we might be better off having a way
for sidecar to assert its health.

Test Plan:
With D48443836, I can see it now fails properly.
```
$ buck run metalos/imaging_initrd/vmtest:test-graph-api-logging-antlir2[shell]
2023-08-17T18:56:20.123823Z ERROR antlir2_vm::vm: Sidecar service at index 0 finished unexpectedly
2023-08-17T18:56:20.123832Z ERROR antlir2_vm::vm: Exit status Ok(
    ExitStatus(
        unix_wait_status(
            256,
        ),
    ),
)
Error: Failed to start sidecar process: `Sidecar service at index 0 finished unexpectedly'
```

Differential Revision: D48443838

fbshipit-source-id: addba9cff5d50a53e15e401495324a692fbe0703