[antlir2][bzl][image_test] Fix RunInfo not recompiling on deps changed
Summary:
`buck run` would not recompile the image or any other dependent artifacts whereas `buck test` would due to missing `with_inputs=True`.

This notably fixes issues like:

```
systemctl get-default failed: Failed to get default target: No such file or directory

Error: systemctl get-default failed: Failed to get default target: No such file or directory
```

where the spec JSON wasn't materialized.

Test Plan:
Modify `fbcode//rl_robot/system/dev/services/image_decoder/ImageDecoderService.cpp` and observe this rebuilding the image:

```
buck2 run fbcode//mode/opt fbcode//rl_robot/system/dev/services/image_decoder:integration_test
```

Rollback Plan:

Reviewed By: vmagro

Differential Revision: D80973228

fbshipit-source-id: 229ba210cbf5224fd2fc61a9930f27ae339e5a01