Don't ignore exception when cleanup fails
Summary:
This makes it more obvious when a subvol cleanup fails because it has nested subvols.

Compare current error message:

```
Container feec698473a8449ca8afc82c62c382bf has been shut down.
Delete subvolume (no-commit): '/data/users/filbranden/scratch/dataZusersZfilbrandenZfbsource/buck-image-out/volume/tmp/TempSubvolumes_hell9aff/systemd-image-from-sendstream:JN0ohlM.JX6F.Kq1s'
ERROR: Could not destroy subvolume/snapshot: Directory not empty
Traceback (most recent call last):
  File "<string>", line 37, in <module>
  File "<string>", line 35, in __run
  File "/usr/local/fbcode/platform007/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/fbcode/platform007/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/users/filbranden/fbsource/fbcode/buck-out/dev/gen/fs_image/nspawn_in_subvol/run#link-tree/fs_image/nspawn_in_subvol/run.py", line 131, in <module>
    )(args.opts, popen_args)
  File "/data/users/filbranden/fbsource/fbcode/buck-out/dev/gen/fs_image/nspawn_in_subvol/run#link-tree/fs_image/nspawn_in_subvol/booted.py", line 40, in run_booted_nspawn
    return _run_booted_nspawn(setup)
  File "/usr/local/fbcode/platform007/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/data/users/filbranden/fbsource/fbcode/buck-out/dev/gen/fs_image/nspawn_in_subvol/run#link-tree/fs_image/nspawn_in_subvol/cmd.py", line 265, in _nspawn_setup
    popen_args=popen_args,
  File "/usr/local/fbcode/platform007/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/data/users/filbranden/fbsource/fbcode/buck-out/dev/gen/fs_image/nspawn_in_subvol/run#link-tree/fs_image/nspawn_in_subvol/cmd.py", line 205, in _snapshot_subvol
    yield nspawn_subvol
  File "/data/users/filbranden/fbsource/fbcode/buck-out/dev/gen/fs_image/nspawn_in_subvol/run#link-tree/tests/temp_subvolumes.py", line 132, in __exit__
    return self._temp_dir_ctx.__exit__(exc_type, exc_val, exc_tb)
  File "/usr/local/fbcode/platform007/lib/python3.7/tempfile.py", line 805, in __exit__
    self.cleanup()
  File "/usr/local/fbcode/platform007/lib/python3.7/tempfile.py", line 809, in cleanup
    _shutil.rmtree(self.name)
  File "/usr/local/fbcode/platform007/lib/python3.7/shutil.py", line 494, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/local/fbcode/platform007/lib/python3.7/shutil.py", line 432, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/local/fbcode/platform007/lib/python3.7/shutil.py", line 432, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/local/fbcode/platform007/lib/python3.7/shutil.py", line 432, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  [Previous line repeated 1 more time]
  File "/usr/local/fbcode/platform007/lib/python3.7/shutil.py", line 452, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/local/fbcode/platform007/lib/python3.7/shutil.py", line 450, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'artifacts_may_require_repo'
```

With the one after this diff:

```
Container 224e2dbbba9b4a42a94ff82b1a9ba01c has been shut down.
Delete subvolume (no-commit): '/data/users/filbranden/scratch/dataZusersZfilbrandenZfbsource/buck-image-out/volume/tmp/TempSubvolumes_d_e21tc4/systemd-image-from-sendstream:JN16knY.HP9t.iyjU'
ERROR: Could not destroy subvolume/snapshot: Directory not empty
ERROR root 2020-03-04 10:24:55,588 Deleting volume /data/users/filbranden/fbsource/fbcode/buck-image-out/volume/tmp/TempSubvolumes_d_e21tc4/systemd-image-from-sendstream:JN16knY.HP9t.iyjU failed.
Traceback (most recent call last):
  File "/data/users/filbranden/fbsource/fbcode/buck-out/dev/gen/fs_image/nspawn_in_subvol/run#link-tree/tests/temp_subvolumes.py", line 130, in __exit__
    subvol.delete()
  File "/data/users/filbranden/fbsource/fbcode/buck-out/dev/gen/fs_image/nspawn_in_subvol/run#link-tree/subvol_utils.py", line 269, in delete
    self.run_as_root(['btrfs', 'subvolume', 'delete', self.path()])
  File "/data/users/filbranden/fbsource/fbcode/buck-out/dev/gen/fs_image/nspawn_in_subvol/run#link-tree/subvol_utils.py", line 235, in run_as_root
    stdout, stderr = proc.communicate(timeout=timeout, input=input)
  File "/usr/local/fbcode/platform007/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/data/users/filbranden/fbsource/fbcode/buck-out/dev/gen/fs_image/nspawn_in_subvol/run#link-tree/subvol_utils.py", line 213, in popen_as_root
    check_popen_returncode(pr)
  File "/data/users/filbranden/fbsource/fbcode/buck-out/dev/gen/fs_image/nspawn_in_subvol/run#link-tree/fs_image/common.py", line 68, in check_popen_returncode
    returncode=proc.returncode, cmd=proc.args,
subprocess.CalledProcessError: Command '['sudo', 'TMP=', '--', 'btrfs', 'subvolume', 'delete', b'/data/users/filbranden/fbsource/fbcode/buck-image-out/volume/tmp/TempSubvolumes_d_e21tc4/systemd-image-from-sendstream:JN16knY.HP9t.iyjU']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "<string>", line 37, in <module>
  File "<string>", line 35, in __run
  File "/usr/local/fbcode/platform007/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/fbcode/platform007/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/users/filbranden/fbsource/fbcode/buck-out/dev/gen/fs_image/nspawn_in_subvol/run#link-tree/fs_image/nspawn_in_subvol/run.py", line 131, in <module>
    )(args.opts, popen_args)
  File "/data/users/filbranden/fbsource/fbcode/buck-out/dev/gen/fs_image/nspawn_in_subvol/run#link-tree/fs_image/nspawn_in_subvol/booted.py", line 40, in run_booted_nspawn
    return _run_booted_nspawn(setup)
  File "/usr/local/fbcode/platform007/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/data/users/filbranden/fbsource/fbcode/buck-out/dev/gen/fs_image/nspawn_in_subvol/run#link-tree/fs_image/nspawn_in_subvol/cmd.py", line 265, in _nspawn_setup
    popen_args=popen_args,
  File "/usr/local/fbcode/platform007/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/data/users/filbranden/fbsource/fbcode/buck-out/dev/gen/fs_image/nspawn_in_subvol/run#link-tree/fs_image/nspawn_in_subvol/cmd.py", line 205, in _snapshot_subvol
    yield nspawn_subvol
  File "/data/users/filbranden/fbsource/fbcode/buck-out/dev/gen/fs_image/nspawn_in_subvol/run#link-tree/tests/temp_subvolumes.py", line 134, in __exit__
    return self._temp_dir_ctx.__exit__(exc_type, exc_val, exc_tb)
  File "/usr/local/fbcode/platform007/lib/python3.7/tempfile.py", line 805, in __exit__
    self.cleanup()
  File "/usr/local/fbcode/platform007/lib/python3.7/tempfile.py", line 809, in cleanup
    _shutil.rmtree(self.name)
  File "/usr/local/fbcode/platform007/lib/python3.7/shutil.py", line 494, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/local/fbcode/platform007/lib/python3.7/shutil.py", line 432, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/local/fbcode/platform007/lib/python3.7/shutil.py", line 432, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/local/fbcode/platform007/lib/python3.7/shutil.py", line 432, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  [Previous line repeated 1 more time]
  File "/usr/local/fbcode/platform007/lib/python3.7/shutil.py", line 452, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/local/fbcode/platform007/lib/python3.7/shutil.py", line 450, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'artifacts_may_require_repo'
```

The message after this diff makes it clear that `btrfs subvolume delete /path/to/snapshot` returned non-zero exit status, so it's easy to reason that what caused the problem is related to that snapshot directory.

Before this diff, we only have a terse `Could not destroy subvolume/snapshot` and the exception complaining about `artifacts_may_require_repo` which is quite irrelevant in this context...

Reviewed By: snarkmaster

Differential Revision: D20242645

fbshipit-source-id: 43bf718967a810e64fc4b71d7fa413801561e58c