[antlir2] better messaging in ensure_single_output
Summary:
This previously defaulted to `optional` for some reason, and did not produce a
useful error message.

Test Plan:
```
❯ buck2 build --show-output fbcode//ads_production_model_training/common:ads_production_model_training.staleness_utils__features_for_cm
File changed: fbcode//antlir/buck2/bzl/ensure_single_output.bzl
File changed: fbcode//antlir/antlir2/bzl/feature/install.bzl
Error running analysis for `fbcode//ads_production_model_training/common:ads_production_model_training.staleness_utils__features_for_cm (ovr_config//platform/linux:x86_64-fbcode-platform010-clang#f3fffce7b700d2dc)`

Caused by:
    Traceback (most recent call last):
      * fbcode/antlir/antlir2/bzl/feature/feature.bzl:132, in <module>
          analysis = _analyze_feature[inline["feature_type"]](**analyze_kwargs)
      * fbcode/antlir/antlir2/bzl/feature/install.bzl:84, in install_analyze
          src = ensure_single_output(src)
      * fbcode/antlir/buck2/bzl/ensure_single_output.bzl:15, in ensure_single_output
          fail("'{}' does not produce any outputs".format(dep.label))
    error: fail: 'fbcode//ads_production_model_training/common:staleness_utils (ovr_config//platform/linux:x86_64-fbcode-platform010-clang#f3fffce7b700d2dc)' does not produce any outputs
      --> fbcode/antlir/buck2/bzl/ensure_single_output.bzl:15:13
       |
    15 |             fail("'{}' does not produce any outputs".format(dep.label))
       |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

ensure that change to `optional=True` does not break antlir
```
❯ buck targets fbcode//antlir/...
```

Reviewed By: zeroxoneb

Differential Revision: D45742396

fbshipit-source-id: 2b69d3cea065c4247186235b9b034de33a310273