[antlir][msdk] cleanup download rule implementation and usages
Summary:
All MSDKs have been rebuilt since the introduction of `msdk.builder`, so this
can now be cleaned up now that everything is consistent wrt component naming
and structure.

NOTE: The centos8 BA MSDK is deleted since it's beyond EOL, so I had to
manually edit the `msdk.bzl` to match everything else

WARNING: It appears that the `eln` and `rpm_builder` MSDKs have been broken for
quite a while so I edited those too, now I will investigate what needs to be
done to unblock them for real.

Test Plan:
```name="They all download and unpack cleanly"
❯ buck uquery 'kind(msdk_download, fbcode//antlir/...)' | xargs buck audit subtargets | cut -d' ' -f1 | xargs buck build
Buck UI: https://www.internalfb.com/buck2/63341177-c48c-4fa6-b371-06c4678a1740
Time elapsed: 35.4s
BUILD SUCCEEDED
```

```name="Spot check some binaries"
❯ buck2 run fbcode//antlir/antlir2/package_managers/dnf/rules/makerepo:makerepo
BUILD SUCCEEDED - starting your binary
error: the following required arguments were not provided:
  --repo-id <REPO_ID>
  --xml-dir <XML_DIR>
  --out <OUT>

Usage: makerepo.sh --repo-id <REPO_ID> --xml-dir <XML_DIR> --out <OUT>

For more information, try '--help'.

❯ buck2 run fbcode//antlir/antlir2/appliance_vm:crosvm
BUILD SUCCEEDED - starting your binary
[2025-05-06T17:41:24.362538587+00:00 ERROR crosvm] arg parsing failed: One of the following subcommands must be present:
    help
    balloon
...
```

for the rest:
waitforsandcastle

Reviewed By: naveedgol

Differential Revision: D74260231

fbshipit-source-id: 69a57fc834dbc7a610ce00ed5130b7614d47431e