[antlir2][vm] use absolute path for qemu-img backing file
Summary:
Our virtual disk file would be created outside the shared repo mount, but our backing file will come from a buck artifact inside repo. Thus we have to set abolute path for the backing file.

From https://www.qemu.org/docs/master/tools/qemu-img.html?highlight=qemu%20img#cmdoption-qemu-img-commands-arg-create
> If a relative path name is given, the backing file is looked up relative to the directory containing FILENAME.

Also fix the missing status check for qemu-img command.

Test Plan:
```
name=With D44926488 (v0.4). Before fix. The success was a lie and backing image path was wrong,counterexample
$ RUST_LOG=trace buck run antlir/antlir2/antlir2_vm:default
2023-05-24T21:23:29.752182Z TRACE antlir2_vm::utils: Executing command: buck-out/v2/gen/fbcode/3f794b0267173c8e/antlir/vm/runtime/__qemu-img__/out/qemu-img create -f qcow2 /run/vm_state/vd0.qcow2 -F raw -b buck-out/v2/gen/fbcode/3f794b0267173c8e/antlir/antlir2/facebook/images/build_appliance/__build-appliance.c9.flavorless__/subvol_symlink
qemu-img: /run/vm_state/vd0.qcow2: Could not open '/run/vm_state/buck-out/v2/gen/fbcode/3f794b0267173c8e/antlir/antlir2/facebook/images/build_appliance/__build-appliance.c9.flavorless__/subvol_symlink': No such file or directory
Could not open backing image.
2023-05-24T21:23:29.760098Z DEBUG antlir2_vm::disk: Created /run/vm_state/vd0.qcow2 for vd0
```
```name=With D44926488 (v0.4). After fix. The error here is due to wrong type of base image but the path is correct
$ buck run antlir/antlir2/antlir2_vm:default
qemu-img: /run/vm_state/vd0.qcow2: 'file' driver requires '/data/users/junjiew/fbsource/buck-out/v2/gen/fbcode/3f794b0267173c8e/antlir/antlir2/facebook/images/build_appliance/__build-appliance.c9.flavorless__/subvol_symlink' to be a regular file
Could not open backing image.
Error: qemu-img failed to create the disk: qemu-img failed
```
```name=With hack in D45009191 (v0.4) and verify it doesn't break VM
$ buck run antlir/antlir2/antlir2_vm:hack
$ RUST_LOG=trace buck run antlir/antlir2/antlir2_vm:antlir2_vm -- isolate --image /data/users/junjiew/fbsource/buck-out/v2/gen/fbcode/3f794b0267173c8e/antlir/antlir2/__build-appliance__/subvol-compile --vm-spec /tmp/vmopts.json --runtime /tmp/runtime.json
<blah blah>
2023-05-24T21:06:42.707692Z TRACE antlir2_vm::utils: Executing command: /data/users/junjiew/fbsource/fbcode/third-party-buck/platform010/build/qemu/bin/qemu-img create -f qcow2 /run/vm_state/vd0.qcow2 -F raw -b /data/users/junjiew/fbsource/buck-out/v2/gen/fbcode/3f794b0267173c8e/antlir/vm/__fbcode__metalos_os_vm__rootfs_eqsb_image-5.6.13-0_fbk21_hardened_6114_gcde3142b1765.btrfs__/out/image.btrfs
<blah and boots to shell>
```

Reviewed By: epilatow

Differential Revision: D46160740

fbshipit-source-id: 90a47eba05c1a84233ddb39ffbf8c2953115ee72