[antlir][vmtest] fix execution in TSAN
Summary:
When run in TSAN, we get errors like
```
OMP: Error #178: Function Can't open SHM2 failed:
OMP: System error #2: No such file or directory
Error: VM run failed: ExitStatus(unix_wait_status(65024))
```

Luckily, all we need to do is to add a tmpfs on `/dev/shm`.

Test Plan:
```name="TSAN passes"
❯ buck2 test fbcode//mode/dev-tsan fbcode//metalos/vm/tests/antlir:rust-test -- is_root
Buck UI: https://www.internalfb.com/buck2/fb6095a1-2060-4c59-92b8-75296909495a
Test UI: https://www.internalfb.com/intern/testinfra/testrun/16607023677718079
Tests finished: Pass 1. Fail 0. Fatal 0. Skip 0. Build failure 0
```

```name="Default mode still passes"
❯ buck2 test fbcode//metalos/vm/tests/antlir:rust-test -- is_root
Buck UI: https://www.internalfb.com/buck2/2a1e95f7-a30c-41e1-95be-1a18b11cd3e4
Test UI: https://www.internalfb.com/intern/testinfra/testrun/5066549828682805
Tests finished: Pass 1. Fail 0. Fatal 0. Skip 0. Build failure 0
```

Reviewed By: justintrudell

Differential Revision: D63710699

fbshipit-source-id: 3daf979e8fa71956a954346e70c775844b733ea7