[antlir2][test] test to ensure reflink copies are used when installing stuff into images
Summary:
This seems like something that's very easy to silently regress.

Especially as I am going to start moving the compiler to more fd-based APIs,
this is important to test.

Test Plan:
```
❯ buck2 test fbcode//antlir/antlir2/test_images/install:test-install-uses-reflink-copy
Buck UI: https://www.internalfb.com/buck2/72334fe9-cca5-4ff9-8fd1-f06f4d924845
Test UI: https://www.internalfb.com/intern/testinfra/testrun/12666373961157575
Network: Up: 17KiB  Down: 1.2KiB  (reSessionID-d18913b7-db86-4eb9-bddd-b38b3a6def53)
Jobs completed: 26. Time elapsed: 5.5s.
Cache hits: 0%. Commands: 4 (cached: 0, remote: 0, local: 4)
Tests finished: Pass 1. Fail 0. Fatal 0. Skip 0. Build failure 0
```

Intentionally regressed to raw bytes copy

```
❯ hg diff
 diff --git a/fbcode/antlir/antlir2/features/install.rs b/fbcode/antlir/antlir2/features/install.rs
 --- a/fbcode/antlir/antlir2/features/install.rs
+++ b/fbcode/antlir/antlir2/features/install.rs
@@ -389,8 +389,20 @@
                     }
                 },
                 None => {
-                    std::fs::copy(&self.src, &dst)?;
-                    let dst_file = File::options().write(true).open(&dst)?;
+                    // std::fs::copy(&self.src, &dst)?;
+                    use std::io::Read;
+                    use std::io::Write;
+                    let mut src = std::fs::File::open(&self.src).expect("failed to open src");
+                    let mut dst_file = File::options().write(true).create(true).open(&dst)?;
+                    let mut buf = [0; 4096];
+                    loop {
+                        let len = src.read(&mut buf).expect("read failed");
+                        if len == 0 {
+                            break;
+                        }
+                        dst_file.write_all(&buf[..len]).expect("write failed");
+                    }
+                    dst_file.sync_all().expect("sync failed");
                     Some(dst_file)
                 }
             };

vmagro@devbig928.frc1 in fbsource
❯ buck test fbcode//antlir/antlir2/test_images/install:test-install-uses-reflink-copy
❯ buck2 test fbcode//antlir/antlir2/test_images/install:test-install-uses-reflink-copy
File changed: fbcode//antlir/antlir2/test_images/install/test_install_uses_reflink_copy.rs
✗ Fail: antlir/antlir2/test_images/install:test-install-uses-reflink-copy - test_file_shares_extents (0.3s)
[
    Extent {
        fe_logical: 0,
        fe_physical: 3882428137472,
        fe_length: 134217728,
        fe_flags: (empty),
    },
    Extent {
        fe_logical: 134217728,
        fe_physical: 3888736370688,
        fe_length: 268435456,
        fe_flags: (empty),
    },
    Extent {
        fe_logical: 402653184,
        fe_physical: 3891554942976,
        fe_length: 134217728,
        fe_flags: LAST,
    },
]
thread 'test_file_shares_extents' panicked at 'all extents should have SHARED flag set', fbcode/antlir/antlir2/test_images/install/test_install_uses_reflink_copy.rs:25:5
stack backtrace:
   0: rust_begin_unwind
             at /home/engshare/third-party2/rust/1.72.1+llvm.15/src/build-platform010/build/rustc-1.72.1-src/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /home/engshare/third-party2/rust/1.72.1+llvm.15/src/build-platform010/build/rustc-1.72.1-src/library/core/src/panicking.rs:67:14
   2: test_file_shares_extents
             at ./fbcode/antlir/antlir2/test_images/install/test_install_uses_reflink_copy.rs:25:5
   3: test_install_uses_reflink_copy::test_file_shares_extents::{closure#0}
             at ./fbcode/antlir/antlir2/test_images/install/test_install_uses_reflink_copy.rs:16:31
   4: <test_install_uses_reflink_copy::test_file_shares_extents::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at /home/engshare/third-party2/rust/1.72.1+llvm.15/src/build-platform010/build/rustc-1.72.1-src/library/core/src/ops/function.rs:250:5
   5: core::ops::function::FnOnce::call_once
             at /home/engshare/third-party2/rust/1.72.1+llvm.15/src/build-platform010/build/rustc-1.72.1-src/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Buck UI: https://www.internalfb.com/buck2/3c7716b9-9e4d-4450-93b4-01184b417a0d
Test UI: https://www.internalfb.com/intern/testinfra/testrun/11540474054316931
Network: Up: 1.5KiB  Down: 5.6KiB  (reSessionID-f51e40d9-4431-4521-9a8c-04a501feee5f)
Jobs completed: 8. Time elapsed: 2.4s.
Cache hits: 0%. Commands: 1 (cached: 0, remote: 0, local: 1)
Tests finished: Pass 0. Fail 1. Fatal 0. Skip 0. Build failure 0
1 TESTS FAILED
  ✗ antlir/antlir2/test_images/install:test-install-uses-reflink-copy - test_file_shares_extents
```

Reviewed By: sergeyfd

Differential Revision: D50992629

fbshipit-source-id: 5ea45fd4e1c6ccffd9e91610eb759efc7a68fc34