Allow passing RUSTC_BOOTSTRAP from env to image_test
Summary:
1.95.0 upgrade is causing breakages in rl_robot code. Tracing through it looks like `-Zunstable-options` added there for tests is causing an issue because antlir image tests do not adopt the `RUSTC_BOOTSTRAP=1` that tpx adds to the environment.

This causes an error at test runtime:

```
error: the option `Z` is only accepted on the nightly compiler
```

Proposal here is to add it centrally to antlir image test, since this flag is often needed for our build infra.

___

overriding_review_checks_triggers_an_audit_and_retroactive_review
Oncall Short Name: rust_foundation

Test Plan:
```
buck test fbcode//mode/dev fbcode//rl_robot/system/dev/services/offboard_relay:integration_test -- --exact 'fbcode//rl_robot/system/dev/services/offboard_relay
:integration_test - tests::test_routing'
```

Differential Revision: D103761940

fbshipit-source-id: c26713da70820f1707928e8999c23e2a735eeb18