vmtest: Switch python-remote-execution example platform to MTIA
Summary:
- Right now only the MTIA platform has chattr installed
- Since I'm building vmtest support specifically for MTIA, it seems natural to switch this anyways

Test Plan:
HG: Before:

```
$ buck test :python-remote-execution -- --run-disabled
...
FileNotFoundError: [Errno 2] No such file or directory: 'chattr'
```

HG: After:

```
$ buck test :python-remote-execution -- --run-disabled
...
AssertionError: No btrfs subvol at /re_cwd/buck-image-out/volume/targets/x86_64--5.6.13-0_fbk21_hardened_6114_gcde3142b1765--image:J0xAMEM.EnCA.4ONG/volume
```

Reviewed By: vmagro

Differential Revision: D47044049

fbshipit-source-id: 94351d85f77ad17a35377f7193682eeee0912820