[antlir][tpx] Add static listing support for Rust VM tests
Summary:
Part 2 of the previous diff, to get rid of the first vm invocation attempt (to list tests)

There is no static lister, so tpx still needs to run one vm to get the list of tests, and then the actual tests [update: not quite for antlir, see below]

I was thinking of adding the existing --list as a static lister instead ( Vinnie pointed out this is already being done in antlir: https://www.internalfb.com/code/fbsource/[f63505b1ed19010215b4096dcfca67d6d6f1fd73]/fbcode/antlir/antlir2/antlir2_vm/src/main.rs?lines=360 )

```
tests_vm_test_inner attestation_files_bundled cmdline_matches_hostconfig edgeos_files_present hostconfig_files_rendered kernel_files_present kernel_matches_hostconfig no_failed_units -Z unstable-options --format=json --exact --show-output
```

Test Plan:
```
buck build --show-output  ti/platform/edgeos/attestrd/edgeos_on_attestrd/tests:tests
fbcode//ti/platform/edgeos/attestrd/edgeos_on_attestrd/tests:tests .../__tests__/test.sh

cat .../test.sh

#!/bin/bash
buck-out/v2/gen/fbcode/4673d78b68c8b534/antlir/antlir2/antlir2_vm/__antlir2_vm__/antlir2_vm \
  test \
  --image=buck-out/v2/gen/fbcode/33eadd9c2afb6f65/antlir/antlir2/antlir2_vm/__container-dir__/container-dir \
  --machine-spec=buck-out/v2/gen/fbcode/fb62e251d37c6beb/ti/platform/edgeos/attestrd/edgeos_on_attestrd/tests/__vm.edgeos__/machine.json \
  --timeout-secs=300 \
  rust \
  buck-out/v2/gen/fbcode/fb62e251d37c6beb/ti/platform/edgeos/attestrd/edgeos_on_attestrd/tests/__tests_vm_test_inner__/tests_vm_test_inner
```

```
$ ./tests_vm_test_inner --list
attestation_files_bundled: test
cmdline_matches_hostconfig: test
edgeos_files_present: test
hostconfig_files_rendered: test
kernel_files_present: test
kernel_matches_hostconfig: test
no_failed_units: test

7 tests, 0 benchmarks

$ ./tests_vm_test_inner --list --format=json
error: The "json" format is only accepted on the nightly compiler with -Z unstable-options

$./tests_vm_test_inner --list -Z unstable-options --format=json
{ "type": "suite", "event": "discovery" }
{ "type": "test", "event": "discovered", "name": "attestation_files_bundled", "ignore": false, "ignore_message": "", "source_path": "fbcode/ti/platform/edgeos/attestrd/edgeos_on_attestrd/tests/tests.rs", "start_line": 34, "start_col": 4, "end_line": 34, "end_col": 29 }
{ "type": "test", "event": "discovered", "name": "cmdline_matches_hostconfig", "ignore": false, "ignore_message": "", "source_path": "fbcode/ti/platform/edgeos/attestrd/edgeos_on_attestrd/tests/tests.rs", "start_line": 164, "start_col": 4, "end_line": 164, "end_col": 30 }
{ "type": "test", "event": "discovered", "name": "edgeos_files_present", "ignore": false, "ignore_message": "", "source_path": "fbcode/ti/platform/edgeos/attestrd/edgeos_on_attestrd/tests/tests.rs", "start_line": 27, "start_col": 4, "end_line": 27, "end_col": 24 }
{ "type": "test", "event": "discovered", "name": "hostconfig_files_rendered", "ignore": false, "ignore_message": "", "source_path": "fbcode/ti/platform/edgeos/attestrd/edgeos_on_attestrd/tests/tests.rs", "start_line": 76, "start_col": 4, "end_line": 76, "end_col": 29 }
{ "type": "test", "event": "discovered", "name": "kernel_files_present", "ignore": false, "ignore_message": "", "source_path": "fbcode/ti/platform/edgeos/attestrd/edgeos_on_attestrd/tests/tests.rs", "start_line": 21, "start_col": 4, "end_line": 21, "end_col": 24 }
{ "type": "test", "event": "discovered", "name": "kernel_matches_hostconfig", "ignore": false, "ignore_message": "", "source_path": "fbcode/ti/platform/edgeos/attestrd/edgeos_on_attestrd/tests/tests.rs", "start_line": 146, "start_col": 4, "end_line": 146, "end_col": 29 }
{ "type": "test", "event": "discovered", "name": "no_failed_units", "ignore": false, "ignore_message": "", "source_path": "fbcode/ti/platform/edgeos/attestrd/edgeos_on_attestrd/tests/tests.rs", "start_line": 105, "start_col": 10, "end_line": 105, "end_col": 25 }
{ "type": "suite", "event": "completed", "tests": 7, "benchmarks": 0, "total": 7, "ignored": 0 }
```

```
buck build --show-output mode/opt buck2/buck2_tpx_cli:buck2_tpx_cli
buck test -c test.v2_test_executor=`pwd`/../buck-out/v2/gen/fbcode/82d2de8c79792266/buck2/buck2_tpx_cli/__buck2_tpx_cli__/buck2_tpx_cli mode/opt ti/platform/edgeos/attestrd/edgeos_on_attestrd/tests:tests
```

ps aux | grep qemu -> only 1 qemu

Differential Revision: D95092880

fbshipit-source-id: 4a9fa3f1044f2f536d9012e7b0d4334cfa5eb283