[antlir2][oss] add support for public rocksdb crate (#233)
Summary:
Pull Request resolved: https://github.com/facebookincubator/antlir/pull/233

antlir2 uses rocksdb for `facts_db`. Internally there is a wrapper, but on
GitHub we need to use the public crate.

Test Plan:
```name="Internal build still works"
❯ buck2 test fbcode//antlir/antlir2/antlir2_facts/...
Buck UI: https://www.internalfb.com/buck2/695d1e59-a047-4521-8fb6-1ff82646da8f
Test UI: https://www.internalfb.com/intern/testinfra/testrun/10414574171647763
Jobs completed: 89638. Time elapsed: 39.0s.
Cache hits: 93%. Commands: 2067 (cached: 1925, remote: 0, local: 142). Fallback: 3/142
Tests finished: Pass 15. Fail 0. Fatal 0. Skip 0. Build failure 0
```

On the GitHub checkout
```
❯ ./buck2 run //antlir/antlir2/antlir2_facts:new-facts-db
Build ID: 2057ac2c-a71d-44ba-8382-45bb89793e4b
Network: Up: 0B  Down: 0B
Jobs completed: 429. Time elapsed: 28.9s.
Cache hits: 0%. Commands: 323 (cached: 0, remote: 0, local: 323)
BUILD SUCCEEDED
error: the following required arguments were not provided:
  --root <ROOT>
  --db <DB>

Usage: new_facts_db --root <ROOT> --db <DB>

For more information, try '--help'.
```

Reviewed By: sergeyfd

Differential Revision: D57126709

fbshipit-source-id: de8cbeb5e541fdd6f6d91fa64921f51e34a3cf44