antlir: Support rpm find-requires for install python binaries
Summary:
Meta python binaries are bundles of:
* An executable, which is sometimes the python interpreter itself
* A collection of one or more shared libraries loaded by python at runtime

Today antlir `feature.install` supports installing required rpms when transitioning to the distro platform using `rpmdeps`.

This diff adds support for the same logic to run when installing python binaries. It does this by looking at the providers from Python to get at the artifacts describing the main executable and antlir-provided shared libraries.

A few caveats:
* We don't want to run rpmdeps on first-party shared libraries, so we filter out any shared libs in the link tree that aren't coming from antlir//antlir/distro/deps/...
* There are some rpm subjects that rpmdeps finds that we _don't_ want to resolve to rpms - specifically, libpython3.x - this is provided by another layer
* For some reason, rpmdeps was finding GLIBC_PRIVATE subjects, so I filtered this out as well.

Currently filtering is hardcoded in this rule, but could be provided as another attr on the rule if needed (hopefully not).

Test Plan:
Set up container, install orchestrator:
```
$ hg diff
 diff --git a/fbcode/tee/orchestrator/server/BUCK b/fbcode/tee/orchestrator/server/BUCK
 --- a/fbcode/tee/orchestrator/server/BUCK
+++ b/fbcode/tee/orchestrator/server/BUCK
@@ -1,4 +1,5 @@
 load("fbcode//fbpkg:fbpkg.bzl", "fbpkg")
+load("fbcode//tee:defs.bzl", "tee")
 load("fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
 load("fbcode_macros//build_defs:cython_library.bzl", "cython_library")
 load("fbcode_macros//build_defs:python_binary.bzl", "python_binary")
@@ -184,11 +185,6 @@
     constraint_overrides = [
         "ovr_config//third-party/pypi/pillow/constraints:11.3.0",
     ],
-    enable_native_python = select({
-        "DEFAULT": True,
-        # Native Python is not quite supported on C10 yet. For now, disable until we get it stable
-        "antlir//antlir/antlir2/os:centos10": False,
-    }),
     main_function = "tee.orchestrator.server.main.main",
     py_version = "3.12",
     deps = [
@@ -203,17 +199,18 @@
     ],
 )

+tee.test_install_layer(
+    name = "layer",
+    src = ":orchestrator",
+    dst = "/usr/local/bin/orchestrator",
+)
+
 python_binary(
     name = "orchestrator_prod",
     srcs = ["main_prod.py"],
     constraint_overrides = [
         "ovr_config//third-party/pypi/pillow/constraints:11.3.0",
     ],
-    enable_native_python = select({
-        "DEFAULT": True,
-        # Native Python is not quite supported on C10 yet. For now, disable until we get it stable
-        "antlir//antlir/antlir2/os:centos10": False,
-    }),
     main_function = "tee.orchestrator.server.main_prod.main",
     py_version = "3.12",
     deps = [
```
then see that everything's installed properly:
```
$ buck run fbcode//mode/opt fbcode//tee/orchestrator/server:layer[container]
Buck UI: https://www.internalfb.com/buck2/0d88bc0f-bbe0-4e38-89f9-e08abe961b93
Network: Up: 89MiB  Down: 294MiB  (reSessionID-304cc045-4e92-4a6d-915b-5973658b2507)
Analyzing targets. Remaining     0/4                                                                                                            4 actions
Executing actions. Remaining     0/5966                                                                                                         1:51:58.7s exec time total
Command: run.      Finished 526 local, 1795 remote, 2436 cache (51% hit)                                                                        16:45.9s exec time cached (14%)
Time elapsed: 4:29.6s
BUILD SUCCEEDED - starting your binary
bash-5.1# /usr/local/bin/orchestrator --help
ERROR    2025-09-18 21:44:32,506 NoPIIStructuredLogger:39 uncategorized: [ORCHESTRATOR_ALLOWED_LOG_START] {"event_type":
         "tee_tokenizer", "event_message": "Unable to load tokenizer"} [ORCHESTRATOR_ALLOWED_LOG_END]
ERROR    2025-09-18 21:44:32,544 NoPIIStructuredLogger:39 uncategorized: [ORCHESTRATOR_ALLOWED_LOG_START] {"event_type":
         "tokenizer_registry", "event_message": "Failed to load default tokenizer tiktoken_v5"}
         [ORCHESTRATOR_ALLOWED_LOG_END]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 985, in <module>
  File "__main__.py", line 982, in __invoke_main
  File "__main__.py", line 597, in main
  File "__par__/meta_only/bootstrap.py", line 111, in run_as_main
  File "__par__/bootstrap.py", line 75, in run_as_main
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 135, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1393, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1366, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1002, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "tee/orchestrator/server/main.py", line 9, in <module>
  File "tee/orchestrator/orchestration/request_handlers/request_handler_registry.py", line 8, in <module>
  File "tee/orchestrator/orchestration/request_handlers/action_suggestions_request/handler.py", line 14, in <module>
  File "tee/orchestrator/orchestration/llama_stack_impl/agent_runner.py", line 20, in <module>
  File "tee/orchestrator/orchestration/utils/request_utils.py", line 32, in <module>
  File "tee/orchestrator/orchestration/utils/tee_tokenizers/tokenizer_registry.py", line 109, in <module>
  File "tee/orchestrator/orchestration/utils/tee_tokenizers/tokenizer_registry.py", line 41, in __init__
  File "tee/orchestrator/orchestration/utils/tee_tokenizers/tokenizer_registry.py", line 50, in _load_default_tokenizers
  File "tee/orchestrator/orchestration/utils/tee_tokenizers/tee_tokenizer.py", line 58, in __init__
  File "tee/orchestrator/orchestration/utils/tee_tokenizers/tee_tokenizer.py", line 48, in __init__
  File "tee/orchestrator/orchestration/utils/tee_tokenizers/tee_tokenizer.py", line 71, in _get_local_tokenizer_file_path
ValueError: Resource path for 'tiktoken_v5' not found or doesn't contain tokenizer.json.
```
rpm plan shows we installed a few necessary RPMs:
```
$ buck log what-ran | grep rpm_plan
Showing commands from: /data/users/skarlage/fbsource/tools/buck2-versions/stable-users run fbcode//mode/opt 'fbcode//tee/orchestrator/server:layer[container]'
build   fbcode//antlir/distro/toolchain/python:layer (fbcode//buck2/platform/execution:linux-x86_64#9380c5be0fc821bb) (rpm_plan package_manager)        local   env -- 'TMPDIR=/data/users/skarlage/fbsource/buck-out/v2/tmp/fbcode/d3e6fa017b91a54e/rpm_plan/package_manager' 'BUCK_SCRATCH_PATH=buck-out/v2/tmp/fbcode/d3e6fa017b91a54e/rpm_plan/package_manager' 'BUCK2_DAEMON_UUID=e7768a3a-4d92-41b2-8826-63f14a0c3970' 'BUCK_BUILD_ID=0d88bc0f-bbe0-4e38-89f9-e08abe961b93' buck-out/v2/gen/fbcode/af1feaf92ff658ec/antlir/antlir2/features/rpm/__plan__/plan '--label=fbcode//antlir/distro/toolchain/python:layer (fbcode//buck2/platform/execution:linux-x86_64#9380c5be0fc821bb)' --rootless '--build-appliance=buck-out/v2/gen-anon/anon_msdk/e9ab0fde28433431antlir/antlir2/facebook/images/build_appliance/centos9/msdk/2b17d6ba00bad002/__dir/__/extracted' '--repodatas=buck-out/v2/gen-anon/anon/af1feaf92ff658ecface43ad683aba7b/__repodata_only_local_repos__/repodatas' '--versionlock=buck-out/v2/gen/fbcode/9380c5be0fc821bb/antlir/antlir2/facebook/flavor/centos9/__versionlock__/versionlock.json' '--versionlock-extend={}' '--exclude-rpm=kernel-devel' '--exclude-rpm=aziot-identity-service' '--exclude-rpm=mft' '--target-arch=x86_64' '--items=buck-out/v2/gen/fbcode/9380c5be0fc821bb/antlir/distro/toolchain/python/__layer__/package_manager/rpm/items.json' '--resolve-cmd=/usr/bin/python3' '--resolve-cmd=buck-out/v2/gen/fbcode/583b08d3ecb8d32c/antlir/antlir2/features/rpm/__resolve__/__resolve__/resolve.py' '--out=buck-out/v2/gen/fbcode/9380c5be0fc821bb/antlir/distro/toolchain/python/__layer__/package_manager/rpm/transaction.json'

$ jq '.install | .[].nevra' < buck-out/v2/gen/fbcode/5eae6e6fcb1e9a83/tee/orchestrator/server/__layer__/package_manager/rpm/transaction.json  | grep double-conversion
"double-conversion-0:3.1.5-6.el9.x86_64"
```

Reviewed By: vmagro

Differential Revision: D82798951

fbshipit-source-id: 5e5c2c7e33a1b695f9cc03518b773d9f084a76a0