vmtest: Delete 9pfs kernel modules mount
Summary: - This doesn't seem necessary since we install the kernel modules in the initrd already: https://fburl.com/code/t3z98pf7

Test Plan:
Are signals sufficient for this change?

My real motivation for this is that it eliminates the one btrfs subvolume dependency for vmtests (well, at least my vmtests), which makes it possible to run vmtests in remote execution workers:

After:

```
$ buck test :python-remote-execution -- --run-disabled
...
AssertionError: No btrfs subvol at /re_cwd/buck-image-out/volume/targets/x86_64--5.6.13-0_fbk21_hardened_6114_gcde3142b1765--image:J0xAMEM.EnCA.4ONG/volume
```

Before:

```
[pdel@devgpu051.atn2 tests]# buck test :python-remote-execution -- --run-disabled
File changed: fbcode//antlir/vm/vm.py
File changed: fbsource//.hgmonitor.status
Buck UI: https://www.internalfb.com/buck2/e46a0b32-db53-4c81-bdda-bfe153bf272b
Test UI: https://www.internalfb.com/intern/testinfra/testrun/8725724446091693
Network: Up: 1.5 GiB  Down: 2.8 GiB  (reSessionID-37c0cf31-2138-404a-a80b-32195a599023)
Jobs completed: 9. Time elapsed: 23.7s. Cache hits: 0%. Commands: 1 (cached: 0, remote: 0, local: 1)
Tests finished: Pass 2. Fail 0. Fatal 0. Skip 0. Build failure 0
```

Reviewed By: vmagro

Differential Revision: D47044050

fbshipit-source-id: 7b9eec6b6a371e582bb2045dcb5e0780174aa067